// The editor side of the database: an object manipulator (IObjMan) reading and
// writing fields by path, inserting into and removing from arrays, iterating
// fields, and a new object saved to disk.
//
// Nival's TestDB covered this, as an executable that ran each check once and
// then returned 0 whatever they found. The checks and their data are carried
// over: the schema is TestDB/TestType.cll, generated by dbcodegen into the TestDB
// library, and the records are TestDB/data. The database runs on a copy of
// them, since opening it writes an index and the last test writes a new object.
//
// Every field is checked through the three routes the editor relies on to agree:
// set and get by path, set by path and read the C++ struct, and write the struct
// and get by path. Fields marked noCode have no struct member; the database
// keeps their values itself, and they are checked by path only.

#include <chrono>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <list>
#include <set>
#include <string>
#include <typeinfo>
#include <unordered_map>
#include <unordered_set>
#include <vector>

// The prelude the database headers and the generated TestType.h expect, in the
// order TestDB/stdafx.h has it.
#include "Misc/Asserts.h"
#include "System/System.h"
#include "Misc/Tools.h"
#include "System/Basic.h"
#include "Misc/Geom.h"
#include "System/Streams.h"
#include "System/BinSaver.h"
#include "System/XmlSaver.h"
#include "System/DB.h"
#include "System/VFSOperations.h"
#include "System/WinVFS.h"
#include "libdb/Db.h"
#include "libdb/EditorDb.h"
#include "libdb/ObjMan.h"
#include "libdb/ObjManIterator.h"
#include "libdb/TypeDef.h"
#include "TestDB/TestDB.h"
#include "TestDB/TestType.h"

#include <boost/uuid/string_generator.hpp>
#include <fmt/format.h>

#include <gtest/gtest.h>

namespace {

boost::uuids::uuid Uuid( const char *pszText )
{
	return boost::uuids::string_generator()( pszText );
}

CVariant Flags( uint32_t nLow, uint32_t nHigh )
{
	const uint32_t flags[2] = { nLow, nHigh };
	return CVariant( flags, sizeof( flags ) );
}

// One database for the whole program, as in the editor: it is opened once on a
// copy of TestDB/data and closed at exit.
class CDatabaseEnvironment : public testing::Environment
{
public:
	static std::filesystem::path dir;

	void SetUp() override
	{
		const auto nStamp = std::chrono::steady_clock::now().time_since_epoch().count();
		dir = std::filesystem::temp_directory_path() / fmt::format( "obk2-libdb-test-{}", nStamp );
		std::filesystem::copy( NTestDB::GetDataDir(), dir, std::filesystem::copy_options::recursive );
		const std::string szDir = dir.generic_string() + "/";

		NVFS::SetMainVFS( NVFS::CreateWinVFS( szDir ) );
		NVFS::SetMainFileCreator( NVFS::CreateWinFileCreator( szDir ) );
		ASSERT_TRUE( NDb::OpenDatabase( NVFS::GetMainVFS(), NVFS::GetMainFileCreator(), NDb::DATABASE_MODE_EDITOR ) );
		for ( const char *pszFile : { "object.xdb", "object2.xdb", "Weapons/USSR/Heavy/A20.xdb", "Weapons/USSR/Light/PPSh.xdb" } )
		{
			EXPECT_TRUE( NDb::RegisterResourceFile( pszFile ) ) << pszFile;
		}
	}

	void TearDown() override
	{
		NDb::CloseDatabase();
		std::error_code ec;
		std::filesystem::remove_all( dir, ec );
	}
};

std::filesystem::path CDatabaseEnvironment::dir;

const testing::Environment *const pDatabaseEnvironment = testing::AddGlobalTestEnvironment( new CDatabaseEnvironment );

// A new MechUnit for each test, so that none depends on what another left.
class CEditorDatabase : public testing::Test
{
protected:
	CObj<NDb::IObjMan> pMan;
	NDb::SMechUnit *pUnit = nullptr;

	void SetUp() override
	{
		pMan = NDb::CreateNewObject( "MechUnit" );
		ASSERT_NE( pMan, nullptr );
		pUnit = dynamic_cast<NDb::SMechUnit *>( pMan->GetObject() );
		ASSERT_NE( pUnit, nullptr );
	}

	int GetSize( const std::string &szArray )
	{
		CVariant value;
		EXPECT_TRUE( pMan->GetValue( szArray, &value ) ) << szArray;
		return int( value );
	}

	void ExpectValue( const std::string &szName, const CVariant &expected )
	{
		CVariant value;
		ASSERT_TRUE( pMan->GetValue( szName, &value ) ) << szName;
		EXPECT_TRUE( value == expected ) << szName;
	}

	void SetAndExpect( const std::string &szName, const CVariant &value )
	{
		ASSERT_TRUE( pMan->SetValue( szName, value ) ) << szName;
		ExpectValue( szName, value );
	}
};

// A field, and two values for it that differ from each other and from the
// default.
struct SFieldValues
{
	const char *pszName;
	bool bHasCode;
	CVariant first;
	CVariant second;
};

std::vector<SFieldValues> ScalarFields()
{
	return {
		{ "Name", true, L"Nice name 1", L"Nice name 2" },
		{ "HP", true, 3.14159f, 2.71828f },
		{ "HasPassability", true, true, false },
		{ "Flags", true, Flags( 0x0f0f0f0f, 0xf0f0f0f0 ), Flags( 0x11223344, 0x55667788 ) },
		{ "DesignerName", true, "Designer 1", "Designer 2" },
		{ "UnitType", true, "UNIT_TYPE_ARMOR_HEAVY", "UNIT_TYPE_AVIA_FIGHTER" },
		{ "Sight", true, 80.0f, 150.0f },
		{ "Speed", true, 10.8f, 20.56f },
		{ "BoundTileRadius", true, 1, 3 },
		{ "Jx.Amplitude", true, 2.3f, 7.8f },
		{ "Jx.Phase", true, 34.23f, 67.34f },
		{ "Jx.Shift", true, 10.45f, 23.53f },
		{ "Jx.Tremble.x", true, 1.2f, 5.6f },
		{ "Jx.Tremble.y", true, 2.4f, 11.2f },
		{ "Jx.Tremble.z", true, 3.6f, 16.8f },
		{ "Jy.Amplitude", true, 6.2f, 4.9f },
		{ "Jy.Phase", true, 33.33f, 66.66f },
		{ "Jy.Shift", true, 55.55f, 44.44f },
		{ "Jy.Tremble.x", true, 4.4f, 7.7f },
		{ "Jy.Tremble.y", true, 8.8f, 15.4f },
		{ "Jy.Tremble.z", true, 13.2f, 23.1f },
		{ "guid", true, Uuid( "51A5BCA0-B663-41a7-8DED-0673AD1C7F60" ), Uuid( "A86000C4-9F09-4241-AA78-F9DA96F3D897" ) },
		{ "Weapon", true, CDBID( "weapons/ussr/heavy/a20.xdb" ), CDBID( "weapons/ussr/light/ppsh.xdb" ) },
		{ "nocodeInt", false, 32, 768 },
		{ "nocodeFloat", false, 99.22f, 95.38f },
		{ "nocodeBool", false, true, false },
		{ "nocodeString", false, "nocode string 1", "nocode string 2" },
		{ "nocodeWString", false, L"nocode wstring 1", L"nocode wstring 2" },
		{ "nocodeGUID", false, Uuid( "51A5BCA0-B663-41a7-8DED-0673AD1C7F60" ), Uuid( "A86000C4-9F09-4241-AA78-F9DA96F3D897" ) },
		{ "nocodeEnumUnitType", false, "UNIT_TYPE_ARMOR_HEAVY", "UNIT_TYPE_AVIA_FIGHTER" },
		{ "nocodeBinaryFlags", false, Flags( 0x0f0f0f0f, 0xf0f0f0f0 ), Flags( 0x11223344, 0x55667788 ) },
	};
}

const SFieldValues &FindField( const std::vector<SFieldValues> &fields, const char *pszName )
{
	for ( const SFieldValues &field : fields )
	{
		if ( strcmp( field.pszName, pszName ) == 0 )
		{
			return field;
		}
	}
	ADD_FAILURE() << "no test values for " << pszName;
	return fields.front();
}

TEST_F( CEditorDatabase, SetThenGetByPath )
{
	for ( const SFieldValues &field : ScalarFields() )
	{
		SetAndExpect( field.pszName, field.first );
		SetAndExpect( field.pszName, field.second );
	}
}

TEST_F( CEditorDatabase, SetByPathReachesTheStruct )
{
	const std::vector<SFieldValues> fields = ScalarFields();
	for ( const SFieldValues &field : fields )
	{
		ASSERT_TRUE( pMan->SetValue( field.pszName, field.second ) ) << field.pszName;
	}
	auto expect = [&]( const CVariant &member, const char *pszName )
	{
		EXPECT_TRUE( member == FindField( fields, pszName ).second ) << pszName;
	};
	expect( pUnit->wszName, "Name" );
	expect( pUnit->fHP, "HP" );
	expect( pUnit->bHasPassability, "HasPassability" );
	expect( pUnit->flags, "Flags" );
	expect( pUnit->szDesignerName, "DesignerName" );
	EXPECT_EQ( pUnit->eUnitType, NDb::SUnitBase::UNIT_TYPE_AVIA_FIGHTER );
	expect( pUnit->fSight, "Sight" );
	expect( pUnit->fSpeed, "Speed" );
	expect( pUnit->nBoundTileRadius, "BoundTileRadius" );
	expect( pUnit->jx.fAmplitude, "Jx.Amplitude" );
	expect( pUnit->jx.fPhase, "Jx.Phase" );
	expect( pUnit->jx.fShift, "Jx.Shift" );
	expect( pUnit->jx.vTremble.x, "Jx.Tremble.x" );
	expect( pUnit->jx.vTremble.y, "Jx.Tremble.y" );
	expect( pUnit->jx.vTremble.z, "Jx.Tremble.z" );
	expect( pUnit->jy.fAmplitude, "Jy.Amplitude" );
	expect( pUnit->jy.fPhase, "Jy.Phase" );
	expect( pUnit->jy.fShift, "Jy.Shift" );
	expect( pUnit->jy.vTremble.x, "Jy.Tremble.x" );
	expect( pUnit->jy.vTremble.y, "Jy.Tremble.y" );
	expect( pUnit->jy.vTremble.z, "Jy.Tremble.z" );
	expect( pUnit->guid, "guid" );
	ASSERT_NE( pUnit->pWeapon, nullptr );
	EXPECT_EQ( pUnit->pWeapon->GetDBID(), FindField( fields, "Weapon" ).second.GetDBID() );
}

TEST_F( CEditorDatabase, StructWritesAreReadByPath )
{
	const std::vector<SFieldValues> fields = ScalarFields();
	auto value = [&]( const char *pszName ) { return FindField( fields, pszName ).first; };
	pUnit->wszName = value( "Name" ).GetWStr();
	pUnit->fHP = float( value( "HP" ) );
	pUnit->bHasPassability = bool( value( "HasPassability" ) );
	memcpy( &pUnit->flags, value( "Flags" ).GetPtr(), sizeof( pUnit->flags ) );
	pUnit->szDesignerName = value( "DesignerName" ).GetStr();
	pUnit->eUnitType = NDb::SUnitBase::UNIT_TYPE_ARMOR_HEAVY;
	pUnit->fSight = float( value( "Sight" ) );
	pUnit->fSpeed = float( value( "Speed" ) );
	pUnit->nBoundTileRadius = int( value( "BoundTileRadius" ) );
	pUnit->jx.fAmplitude = float( value( "Jx.Amplitude" ) );
	pUnit->jx.fPhase = float( value( "Jx.Phase" ) );
	pUnit->jx.fShift = float( value( "Jx.Shift" ) );
	pUnit->jx.vTremble = CVec3( float( value( "Jx.Tremble.x" ) ), float( value( "Jx.Tremble.y" ) ), float( value( "Jx.Tremble.z" ) ) );
	pUnit->jy.fAmplitude = float( value( "Jy.Amplitude" ) );
	pUnit->jy.fPhase = float( value( "Jy.Phase" ) );
	pUnit->jy.fShift = float( value( "Jy.Shift" ) );
	pUnit->jy.vTremble = CVec3( float( value( "Jy.Tremble.x" ) ), float( value( "Jy.Tremble.y" ) ), float( value( "Jy.Tremble.z" ) ) );
	memcpy( &pUnit->guid, value( "guid" ).GetPtr(), sizeof( pUnit->guid ) );
	pUnit->pWeapon = static_cast<NDb::SWeapon *>( NDb::GetObject( value( "Weapon" ).GetDBID() ) );
	for ( const SFieldValues &field : fields )
	{
		if ( field.bHasCode )
		{
			ExpectValue( field.pszName, field.first );
		}
	}
}

// Five values for each kind of simple array, in the order the checks expect
// them to end up.
struct SArrayValues
{
	const char *pszName;
	CVariant values[5];
};

std::vector<SArrayValues> SimpleArrays()
{
	const CVariant guids[5] = {
		Uuid( "C0968E41-7392-4c8a-9AE7-D20CDDE48BD3" ), Uuid( "83F99F40-717C-4598-B18F-959F37FCACEA" ),
		Uuid( "24EAE67F-21F0-4e7f-AB58-A2591DA1DC9E" ), Uuid( "96855F55-EF5B-4acc-8770-8D4A1EB57271" ),
		Uuid( "BF101B1E-8FDD-47a2-8AA1-E179BFA88177" ) };
	const CVariant flags[5] = {
		Flags( 0x0f0f0f0f, 0xf0f0f0f0 ), Flags( 0x11223344, 0x55667788 ), Flags( 0x12345678, 0x9abcdef0 ),
		Flags( 0x87654321, 0x0fedcba9 ), Flags( 0x44332211, 0x88776655 ) };
	std::vector<SArrayValues> arrays;
	for ( const char *pszSuffix : { "", "Nocode" } )
	{
		auto name = [pszSuffix]( const char *pszBase ) { return fmt::format( "{}{}", pszBase, pszSuffix ); };
		// the names have to outlive this function
		static std::set<std::string> names;
		auto add = [&]( const char *pszBase, std::initializer_list<CVariant> values )
		{
			SArrayValues array;
			array.pszName = names.insert( name( pszBase ) ).first->c_str();
			std::copy( values.begin(), values.end(), array.values );
			arrays.push_back( array );
		};
		add( "SimpleArrayInt", { 1, 2, 3, 4, 5 } );
		add( "SimpleArrayFloat", { 1.1f, 2.2f, 3.3f, 4.4f, 5.5f } );
		add( "SimpleArrayGUID", { guids[0], guids[1], guids[2], guids[3], guids[4] } );
		add( "SimpleArrayBinaryFlags", { flags[0], flags[1], flags[2], flags[3], flags[4] } );
		add( "SimpleArrayEnumUnitType", { "UNIT_TYPE_INFANTRY_SNIPER", "UNIT_TYPE_ARMOR_MEDIUM", "UNIT_TYPE_ARMOR_HEAVY", "UNIT_TYPE_AVIA_FIGHTER", "UNIT_TYPE_AUTO_ENGINEER" } );
		add( "SimpleArrayString", { "Test string 0", "Test string 1", "Test string 2", "Test string 3", "Test string 4" } );
		add( "SimpleArrayWString", { L"Очень клёвый wstring 0", L"Очень клёвый wstring 1", L"Очень клёвый wstring 2", L"Очень клёвый wstring 3", L"Очень клёвый wstring 4" } );
	}
	arrays.push_back( { "Weapons", { CDBID( "weapons/ussr/heavy/a20.xdb" ), CDBID( "weapons/ussr/light/ppsh.xdb" ),
		CDBID( "weapons/ussr/heavy/a20.xdb" ), CDBID( "weapons/ussr/light/ppsh.xdb" ), CDBID( "weapons/ussr/heavy/a20.xdb" ) } } );
	return arrays;
}

std::string Element( const std::string &szArray, int nIndex )
{
	return fmt::format( "{}.[{}]", szArray, nIndex );
}

// Builds the array [0 1 2 3 4] out of inserts at the front, the back (-1) and
// the middle, then removes the first, the last and a middle element, checking
// every element after each step. SetElement and ExpectElement write and check
// whatever element i holds, which for a struct array is several fields.
template <class TSet, class TExpect>
void InsertAndRemove( NDb::IObjMan *pMan, const std::string &szArray, TSet setElement, TExpect expectElement )
{
	auto size = [&]()
	{
		CVariant value;
		EXPECT_TRUE( pMan->GetValue( szArray, &value ) ) << szArray;
		return int( value );
	};
	auto expectAll = [&]( std::initializer_list<int> values )
	{
		ASSERT_EQ( size(), int( values.size() ) ) << szArray;
		int nIndex = 0;
		for ( const int nValue : values )
		{
			expectElement( nIndex++, nValue );
		}
	};
	ASSERT_TRUE( pMan->Insert( szArray, 0, 2 ) ) << szArray;
	setElement( 0, 0 );
	setElement( 1, 1 );
	expectAll( { 0, 1 } );
	ASSERT_TRUE( pMan->Insert( szArray, -1, 2 ) ) << szArray;
	setElement( 2, 3 );
	setElement( 3, 4 );
	expectAll( { 0, 1, 3, 4 } );
	ASSERT_TRUE( pMan->Insert( szArray, 2, 1 ) ) << szArray;
	setElement( 2, 2 );
	expectAll( { 0, 1, 2, 3, 4 } );
	ASSERT_TRUE( pMan->Remove( szArray, 0, 1 ) ) << szArray;
	expectAll( { 1, 2, 3, 4 } );
	ASSERT_TRUE( pMan->Remove( szArray, 3, 1 ) ) << szArray;
	expectAll( { 1, 2, 3 } );
	ASSERT_TRUE( pMan->Remove( szArray, 1, 1 ) ) << szArray;
	expectAll( { 1, 3 } );
}

TEST_F( CEditorDatabase, SimpleArraysInsertAndRemove )
{
	for ( const SArrayValues &array : SimpleArrays() )
	{
		SCOPED_TRACE( array.pszName );
		InsertAndRemove( pMan, array.pszName,
			[&]( int nIndex, int nValue ) { SetAndExpect( Element( array.pszName, nIndex ), array.values[nValue] ); },
			[&]( int nIndex, int nValue ) { ExpectValue( Element( array.pszName, nIndex ), array.values[nValue] ); } );
	}
}

// The fields of one Struct1, with every field distinct across the five.
std::vector<std::pair<std::string, CVariant>> Struct1Fields( int nValue )
{
	static const char *const unitTypes[5] = {
		"UNIT_TYPE_INFANTRY_SNIPER", "UNIT_TYPE_ARMOR_MEDIUM", "UNIT_TYPE_ARMOR_HEAVY", "UNIT_TYPE_AVIA_FIGHTER", "UNIT_TYPE_SPG_ASSAULT" };
	static const char *const guids[5] = {
		"A3965C8E-B3EA-472f-8289-4117D37BC8AA", "D355FB02-F8C8-4b16-A387-73F3FCBE4A5B", "368B1489-11B0-45d5-9BE2-28148111A71A",
		"4EC8482F-C39F-41fb-AA5D-1900E43D6BE6", "C6DA102B-7AE6-4ce8-AB94-C222A7A2721E" };
	const int n = nValue + 1;
	return {
		{ "TypeInt", n },
		{ "TypeFloat", float( n ) },
		{ "TypeBool", n % 2 == 1 },
		{ "TypeGUID", Uuid( guids[nValue] ) },
		{ "TypeString", fmt::format( "test string {}", n ) },
		{ "TypeWString", L"test wstring " + std::to_wstring( n ) },
		{ "TypeEnumUnitType", unitTypes[nValue] },
		{ "TypeBinaryFlags", Flags( 0x01010101u * n, 0x10101010u * n ) },
	};
}

void Struct1InsertAndRemove( CEditorDatabase *pTest, NDb::IObjMan *pMan, const std::string &szArray )
{
	SCOPED_TRACE( szArray );
	auto forEachField = [&]( int nIndex, int nValue, auto check )
	{
		for ( const auto &[szField, value] : Struct1Fields( nValue ) )
		{
			check( Element( szArray, nIndex ) + "." + szField, value );
		}
	};
	auto expectField = [&]( const std::string &szName, const CVariant &expected )
	{
		CVariant value;
		ASSERT_TRUE( pMan->GetValue( szName, &value ) ) << szName;
		EXPECT_TRUE( value == expected ) << szName;
	};
	InsertAndRemove( pMan, szArray,
		[&]( int nIndex, int nValue )
		{
			forEachField( nIndex, nValue, [&]( const std::string &szName, const CVariant &value )
			{
				ASSERT_TRUE( pMan->SetValue( szName, value ) ) << szName;
				expectField( szName, value );
			} );
		},
		[&]( int nIndex, int nValue ) { forEachField( nIndex, nValue, expectField ); } );
}

TEST_F( CEditorDatabase, StructArrayInsertAndRemove )
{
	Struct1InsertAndRemove( this, pMan, "ComplexArrayStruct1" );
}

// An array of structs that each hold an array of structs.
TEST_F( CEditorDatabase, ArrayInArrayInsertAndRemove )
{
	const std::string szArray = "ComplexArrayStruct2";
	ASSERT_TRUE( pMan->Insert( szArray, 0, 2 ) );
	EXPECT_EQ( GetSize( szArray ), 2 );
	Struct1InsertAndRemove( this, pMan, szArray + ".[0].Structs" );
	Struct1InsertAndRemove( this, pMan, szArray + ".[1].Structs" );
	ASSERT_TRUE( pMan->Insert( szArray, -1, 2 ) );
	EXPECT_EQ( GetSize( szArray ), 4 );
	Struct1InsertAndRemove( this, pMan, szArray + ".[2].Structs" );
	Struct1InsertAndRemove( this, pMan, szArray + ".[3].Structs" );
	ASSERT_TRUE( pMan->Insert( szArray, 2, 1 ) );
	EXPECT_EQ( GetSize( szArray ), 5 );
	Struct1InsertAndRemove( this, pMan, szArray + ".[2].Structs" );

	ASSERT_TRUE( pMan->Remove( szArray, 0, 1 ) );
	EXPECT_EQ( GetSize( szArray ), 4 );
	ASSERT_TRUE( pMan->Remove( szArray, 3, 1 ) );
	EXPECT_EQ( GetSize( szArray ), 3 );
	ASSERT_TRUE( pMan->Remove( szArray, 1, 1 ) );
	EXPECT_EQ( GetSize( szArray ), 2 );

	// setting an array's own value resizes it
	ASSERT_TRUE( pMan->SetValue( szArray, 3 ) );
	EXPECT_EQ( GetSize( szArray ), 3 );
	ASSERT_TRUE( pMan->SetValue( szArray + ".[2].Structs", 4 ) );
	EXPECT_EQ( GetSize( szArray + ".[2].Structs" ), 4 );
	ASSERT_TRUE( pMan->SetValue( szArray + ".[2].Structs.[1].TypeInt", 1234567890 ) );
	ASSERT_EQ( pUnit->complexArrayStruct2.size(), 3u );
	ASSERT_EQ( pUnit->complexArrayStruct2[2].structs.size(), 4u );
	EXPECT_EQ( pUnit->complexArrayStruct2[2].structs[1].nTypeInt, 1234567890 );
}

// A field as the iterator reports it: its full path, its ETypeType and its type
// name. Hidden fields are skipped unless the iterator is asked for them.
struct SIteratedField
{
	std::string szName;
	int nType;
	std::string szTypeName;
	bool bHidden;
};

std::vector<SIteratedField> Struct1IteratedFields( const std::string &szPrefix )
{
	return {
		{ szPrefix + "TypeInt", NDb::NTypeDef::TYPE_TYPE_INT, "int", false },
		{ szPrefix + "TypeFloat", NDb::NTypeDef::TYPE_TYPE_FLOAT, "float", true },
		{ szPrefix + "TypeBool", NDb::NTypeDef::TYPE_TYPE_BOOL, "bool", false },
		{ szPrefix + "TypeGUID", NDb::NTypeDef::TYPE_TYPE_GUID, "GUID", true },
		{ szPrefix + "TypeString", NDb::NTypeDef::TYPE_TYPE_STRING, "string", true },
		{ szPrefix + "TypeWString", NDb::NTypeDef::TYPE_TYPE_WSTRING, "wstring", false },
		{ szPrefix + "TypeEnumUnitType", NDb::NTypeDef::TYPE_TYPE_ENUM, "UnitType", false },
		{ szPrefix + "TypeBinaryFlags", NDb::NTypeDef::TYPE_TYPE_BINARY, "Flags", false },
	};
}

// What iterating object2.xdb has to report, in order. Every array in it holds
// five elements, except Weapons, which is empty.
std::vector<SIteratedField> Object2IteratedFields()
{
	using namespace NDb::NTypeDef;
	std::vector<SIteratedField> fields = {
		{ "Name", TYPE_TYPE_WSTRING, "wstring", false },
		{ "HP", TYPE_TYPE_FLOAT, "float", false },
		{ "HasPassability", TYPE_TYPE_BOOL, "bool", false },
		{ "Flags", TYPE_TYPE_BINARY, "Flags", false },
		{ "DesignerName", TYPE_TYPE_STRING, "string", false },
		{ "UnitType", TYPE_TYPE_ENUM, "UnitType", false },
		{ "Sight", TYPE_TYPE_FLOAT, "float", false },
		{ "Speed", TYPE_TYPE_FLOAT, "float", false },
		{ "BoundTileRadius", TYPE_TYPE_INT, "int", false },
	};
	for ( const char *pszJogging : { "Jx", "Jy" } )
	{
		const std::string sz = pszJogging;
		fields.insert( fields.end(), {
			{ sz, TYPE_TYPE_STRUCT, "Jogging", false },
			{ sz + ".Amplitude", TYPE_TYPE_FLOAT, "float", false },
			{ sz + ".Phase", TYPE_TYPE_FLOAT, "float", false },
			{ sz + ".Shift", TYPE_TYPE_FLOAT, "float", false },
			{ sz + ".Tremble", TYPE_TYPE_STRUCT, "Vec3", false },
			{ sz + ".Tremble.x", TYPE_TYPE_FLOAT, "float", false },
			{ sz + ".Tremble.y", TYPE_TYPE_FLOAT, "float", false },
			{ sz + ".Tremble.z", TYPE_TYPE_FLOAT, "float", false },
		} );
	}
	fields.insert( fields.end(), {
		{ "guid", TYPE_TYPE_GUID, "GUID", false },
		{ "nocodeInt", TYPE_TYPE_INT, "int", false },
		{ "nocodeFloat", TYPE_TYPE_FLOAT, "float", false },
		{ "nocodeBool", TYPE_TYPE_BOOL, "bool", false },
		{ "nocodeString", TYPE_TYPE_STRING, "string", false },
		{ "nocodeWString", TYPE_TYPE_WSTRING, "wstring", false },
		{ "nocodeGUID", TYPE_TYPE_GUID, "GUID", false },
		{ "nocodeEnumUnitType", TYPE_TYPE_ENUM, "UnitType", false },
		{ "nocodeBinaryFlags", TYPE_TYPE_BINARY, "Flags", false },
	} );
	const std::pair<const char *, std::pair<int, const char *>> simpleArrays[] = {
		{ "SimpleArrayInt", { TYPE_TYPE_INT, "int" } },
		{ "SimpleArrayFloat", { TYPE_TYPE_FLOAT, "float" } },
		{ "SimpleArrayGUID", { TYPE_TYPE_GUID, "GUID" } },
		{ "SimpleArrayBinaryFlags", { TYPE_TYPE_BINARY, "Flags" } },
		{ "SimpleArrayEnumUnitType", { TYPE_TYPE_ENUM, "UnitType" } },
		{ "SimpleArrayString", { TYPE_TYPE_STRING, "string" } },
		{ "SimpleArrayWString", { TYPE_TYPE_WSTRING, "wstring" } },
	};
	for ( const char *pszSuffix : { "", "Nocode" } )
	{
		for ( const auto &[pszArray, type] : simpleArrays )
		{
			const std::string szArray = std::string( pszArray ) + pszSuffix;
			fields.push_back( { szArray, TYPE_TYPE_ARRAY, "array", false } );
			for ( int i = 0; i < 5; ++i )
			{
				fields.push_back( { Element( szArray, i ), type.first, type.second, false } );
			}
		}
	}
	fields.push_back( { "ComplexArrayStruct1", TYPE_TYPE_ARRAY, "array", false } );
	for ( int i = 0; i < 5; ++i )
	{
		fields.push_back( { Element( "ComplexArrayStruct1", i ), TYPE_TYPE_STRUCT, "Struct1", false } );
		const std::vector<SIteratedField> struct1 = Struct1IteratedFields( Element( "ComplexArrayStruct1", i ) + "." );
		fields.insert( fields.end(), struct1.begin(), struct1.end() );
	}
	fields.push_back( { "ComplexArrayStruct2", TYPE_TYPE_ARRAY, "array", false } );
	for ( int i = 0; i < 5; ++i )
	{
		const std::string szStruct2 = Element( "ComplexArrayStruct2", i );
		fields.push_back( { szStruct2, TYPE_TYPE_STRUCT, "Struct2", false } );
		fields.push_back( { szStruct2 + ".Structs", TYPE_TYPE_ARRAY, "array", false } );
		for ( int j = 0; j < 5; ++j )
		{
			fields.push_back( { Element( szStruct2 + ".Structs", j ), TYPE_TYPE_STRUCT, "Struct1", false } );
			const std::vector<SIteratedField> struct1 = Struct1IteratedFields( Element( szStruct2 + ".Structs", j ) + "." );
			fields.insert( fields.end(), struct1.begin(), struct1.end() );
		}
		fields.push_back( { szStruct2 + ".guids", TYPE_TYPE_ARRAY, "array", false } );
		for ( int j = 0; j < 5; ++j )
		{
			fields.push_back( { Element( szStruct2 + ".guids", j ), TYPE_TYPE_GUID, "GUID", false } );
		}
	}
	// a reference's type is named "ref" whatever it points at; object2.xdb leaves
	// Weapons empty
	fields.push_back( { "Weapon", TYPE_TYPE_REF, "ref", false } );
	fields.push_back( { "Weapons", TYPE_TYPE_ARRAY, "array", false } );
	return fields;
}

struct SReportedField
{
	std::string szName;
	int nType;
	std::string szTypeName;
	bool operator==( const SReportedField &other ) const
	{
		return szName == other.szName && nType == other.nType && szTypeName == other.szTypeName;
	}
};

void PrintTo( const SReportedField &field, std::ostream *pStream )
{
	*pStream << field.szName << " " << field.nType << " " << field.szTypeName;
}

std::vector<SReportedField> Iterate( NDb::IObjMan *pMan, bool bShowHidden )
{
	std::vector<SReportedField> res;
	for ( CObj<NDb::IObjManIterator> pIt = pMan->CreateIterator( bShowHidden ); !pIt->IsEnd(); pIt->Next() )
	{
		const NDb::NTypeDef::STypeStructBase::SField *pField = pIt->GetDesc();
		res.push_back( { pIt->GetName(), int( pField->pType->eType ), pField->pType->GetTypeName() } );
	}
	return res;
}

std::vector<SReportedField> Expected( const std::vector<SIteratedField> &fields, bool bShowHidden )
{
	std::vector<SReportedField> res;
	for ( const SIteratedField &field : fields )
	{
		if ( bShowHidden || !field.bHidden )
		{
			res.push_back( { field.szName, field.nType, field.szTypeName } );
		}
	}
	return res;
}

TEST( EditorDatabaseIterator, ReportsEveryFieldInOrder )
{
	CObj<NDb::IObjMan> pMan = NDb::GetManipulator( CDBID( "object2.xdb" ) );
	ASSERT_NE( pMan, nullptr );
	for ( const bool bShowHidden : { false, true } )
	{
		SCOPED_TRACE( bShowHidden ? "hidden shown" : "hidden skipped" );
		EXPECT_EQ( Iterate( pMan, bShowHidden ), Expected( Object2IteratedFields(), bShowHidden ) );
	}
}

// A manipulator made for one array element iterates that element's fields,
// named relative to it.
TEST( EditorDatabaseIterator, ElementManipulatorReportsTheElementsFields )
{
	CObj<NDb::IObjMan> pMan = NDb::GetManipulator( CDBID( "object2.xdb" ) );
	ASSERT_NE( pMan, nullptr );
	CObj<NDb::IObjMan> pElement = pMan->CreateManipulator( "ComplexArrayStruct2.[2].Structs.[3]" );
	ASSERT_NE( pElement, nullptr );
	for ( const bool bShowHidden : { false, true } )
	{
		SCOPED_TRACE( bShowHidden ? "hidden shown" : "hidden skipped" );
		EXPECT_EQ( Iterate( pElement, bShowHidden ), Expected( Struct1IteratedFields( "" ), bShowHidden ) );
	}
}

TEST( EditorDatabaseIterator, DescribesAFieldByPath )
{
	CObj<NDb::IObjMan> pMan = NDb::GetManipulator( CDBID( "object2.xdb" ) );
	ASSERT_NE( pMan, nullptr );
	CObj<NDb::IObjMan> pElement = pMan->CreateManipulator( "ComplexArrayStruct2.[2].Structs.[4]" );
	ASSERT_NE( pElement, nullptr );
	using namespace NDb::NTypeDef;
	const std::pair<NDb::IObjMan *, SReportedField> cases[] = {
		{ pMan, { "ComplexArrayStruct2.[2].Structs.[4].TypeBinaryFlags", TYPE_TYPE_BINARY, "Flags" } },
		{ pMan, { "ComplexArrayStruct2.[2].Structs.[4]", TYPE_TYPE_STRUCT, "Struct1" } },
		{ pMan, { "ComplexArrayStruct2.[2].Structs", TYPE_TYPE_ARRAY, "array" } },
		{ pMan, { "ComplexArrayStruct2.[2]", TYPE_TYPE_STRUCT, "Struct2" } },
		{ pMan, { "ComplexArrayStruct2", TYPE_TYPE_ARRAY, "array" } },
		{ pElement, { "TypeBinaryFlags", TYPE_TYPE_BINARY, "Flags" } },
		{ pElement, { "TypeString", TYPE_TYPE_STRING, "string" } },
	};
	for ( const auto &[pSubject, expected] : cases )
	{
		const STypeStructBase::SField *pField = pSubject->GetDesc( expected.szName );
		ASSERT_NE( pField, nullptr ) << expected.szName;
		EXPECT_EQ( ( SReportedField{ expected.szName, int( pField->pType->eType ), pField->pType->GetTypeName() } ), expected );
	}
}

// A new object, filled in, registered and saved, is written to its file with its
// values and attributes.
TEST_F( CEditorDatabase, NewObjectIsSaved )
{
	ASSERT_TRUE( pMan->SetValue( "Jx.Tremble.y", 9876.4f ) );
	ASSERT_TRUE( pMan->SetValue( "Name", L"This is a nice test!" ) );
	pMan->SetAttribute( "Owner", L"Юрий Блажевич" );
	pMan->SetAttribute( "MOD", L"Мой любимый MOD" );
	ASSERT_TRUE( NDb::AddNewObject( "object3.xdb", CDBID( "object3.xdb" ), pMan ) );
	NDb::SaveChanges();
	EXPECT_EQ( NDb::GetLastSaveError(), "" );

	const std::filesystem::path file = CDatabaseEnvironment::dir / "object3.xdb";
	ASSERT_TRUE( std::filesystem::exists( file ) );
	CFileStream stream( file.generic_string(), CFileStream::WIN_READ_ONLY );
	ASSERT_TRUE( stream.IsOk() );
	std::string szText( stream.GetSize(), '\0' );
	stream.Read( szText.data(), int( szText.size() ) );
	EXPECT_NE( szText.find( "This is a nice test!" ), std::string::npos ) << szText;
	EXPECT_NE( szText.find( "9876.4" ), std::string::npos ) << szText;
	EXPECT_NE( szText.find( "Юрий Блажевич" ), std::string::npos ) << szText;

	CObj<NDb::IObjMan> pSaved = NDb::GetManipulator( CDBID( "object3.xdb" ) );
	ASSERT_NE( pSaved, nullptr );
	EXPECT_EQ( pSaved->GetAttribute( "MOD" ), L"Мой любимый MOD" );
}

} // namespace
