include_directories(${CMAKE_CURRENT_SOURCE_DIR})

add_subdirectory("Misc")
add_subdirectory("System")
add_subdirectory("Game")
add_subdirectory("GameX")
add_subdirectory("Main")
add_subdirectory("Input")
add_subdirectory("Image")
add_subdirectory("AILogic")
add_subdirectory("Script")
add_subdirectory("3Dmotor")
add_subdirectory("MemoryLib")
add_subdirectory("3DLib")
add_subdirectory("Scintilla")
add_subdirectory("SceneB2")
add_subdirectory("UI")
add_subdirectory("Sound")
add_subdirectory("UISpecificB2")
add_subdirectory("Net")
add_subdirectory("Stats_B2_M1")
add_subdirectory("Common_RTS_AI")
add_subdirectory("Client")
add_subdirectory("Server_Client_Common")
add_subdirectory("B2_M1_World")
add_subdirectory("DebugTools")
add_subdirectory("B2_M1_Terrain")
add_subdirectory("libdb")
add_subdirectory("Parser")

if(BUILD_EDITOR)
    add_subdirectory("vendor/stingray")

    add_subdirectory("MapEditorLib")
    add_subdirectory("ED_Common")
    add_subdirectory("ED_B2_M1")
    add_subdirectory("ED_B2")
    add_subdirectory("ED_RTS")
    add_subdirectory("MapEditor")
    add_subdirectory("B2_MapEditor")
endif()
if(BUILD_SERVER)
    add_subdirectory("TestClient")
    add_subdirectory("Server")
endif()
