#include "stdafx.h"

#include "Tools_SysCodes.h"

CWMMnemonicCodes::CWMMnemonicCodes() : CMnemonicsCollector<UINT>( 0, "" )
{
	Insert( WM_NULL, "WM_NULL" );
	Insert( WM_CREATE, "WM_CREATE" );
	Insert( WM_DESTROY, "WM_DESTROY" );
	Insert( WM_MOVE, "WM_MOVE" );
	Insert( WM_SIZE, "WM_SIZE" );
	Insert( WM_ACTIVATE, "WM_ACTIVATE" );
	Insert( WM_SETFOCUS, "WM_SETFOCUS" );
	Insert( WM_KILLFOCUS, "WM_KILLFOCUS" );
	Insert( WM_ENABLE, "WM_ENABLE" );
	Insert( WM_SETREDRAW, "WM_SETREDRAW" );
	Insert( WM_SETTEXT, "WM_SETTEXT" );
	Insert( WM_GETTEXT, "WM_GETTEXT" );
	Insert( WM_GETTEXTLENGTH, "WM_GETTEXTLENGTH" );
	Insert( WM_PAINT, "WM_PAINT" );
	Insert( WM_CLOSE, "WM_CLOSE" );
	Insert( WM_QUERYENDSESSION, "WM_QUERYENDSESSION" );
	Insert( WM_QUIT, "WM_QUIT" );
	Insert( WM_QUERYOPEN, "WM_QUERYOPEN" );
	Insert( WM_ERASEBKGND, "WM_ERASEBKGND" );
	Insert( WM_SYSCOLORCHANGE, "WM_SYSCOLORCHANGE" );
	Insert( WM_ENDSESSION, "WM_ENDSESSION" );
	Insert( WM_SHOWWINDOW, "WM_SHOWWINDOW" );
	Insert( WM_WININICHANGE, "WM_WININICHANGE" );
	Insert( WM_DEVMODECHANGE, "WM_DEVMODECHANGE" );
	Insert( WM_ACTIVATEAPP, "WM_ACTIVATEAPP" );
	Insert( WM_FONTCHANGE, "WM_FONTCHANGE" );
	Insert( WM_TIMECHANGE, "WM_TIMECHANGE" );
	Insert( WM_CANCELMODE, "WM_CANCELMODE" );
	Insert( WM_SETCURSOR, "WM_SETCURSOR" );
	Insert( WM_MOUSEACTIVATE, "WM_MOUSEACTIVATE" );
	Insert( WM_CHILDACTIVATE, "WM_CHILDACTIVATE" );
	Insert( WM_QUEUESYNC, "WM_QUEUESYNC" );
	Insert( WM_GETMINMAXINFO, "WM_GETMINMAXINFO" );
	Insert( WM_PAINTICON, "WM_PAINTICON" );
	Insert( WM_ICONERASEBKGND, "WM_ICONERASEBKGND" );
	Insert( WM_NEXTDLGCTL, "WM_NEXTDLGCTL" );
	Insert( WM_SPOOLERSTATUS, "WM_SPOOLERSTATUS" );
	Insert( WM_DRAWITEM, "WM_DRAWITEM" );
	Insert( WM_MEASUREITEM, "WM_MEASUREITEM" );
	Insert( WM_DELETEITEM, "WM_DELETEITEM" );
	Insert( WM_VKEYTOITEM, "WM_VKEYTOITEM" );
	Insert( WM_CHARTOITEM, "WM_CHARTOITEM" );
	Insert( WM_SETFONT, "WM_SETFONT" );
	Insert( WM_GETFONT, "WM_GETFONT" );
	Insert( WM_SETHOTKEY, "WM_SETHOTKEY" );
	Insert( WM_GETHOTKEY, "WM_GETHOTKEY" );
	Insert( WM_QUERYDRAGICON, "WM_QUERYDRAGICON" );
	Insert( WM_COMPAREITEM, "WM_COMPAREITEM" );
	Insert( WM_COMPACTING, "WM_COMPACTING" );
	Insert( WM_COMMNOTIFY, "WM_COMMNOTIFY" );
	Insert( WM_WINDOWPOSCHANGING, "WM_WINDOWPOSCHANGING" );
	Insert( WM_WINDOWPOSCHANGED, "WM_WINDOWPOSCHANGED" );
	Insert( WM_POWER, "WM_POWER" );
	Insert( WM_COPYDATA, "WM_COPYDATA" );
	Insert( WM_CANCELJOURNAL, "WM_CANCELJOURNAL" );
	Insert( WM_NOTIFY, "WM_NOTIFY" );
	Insert( WM_INPUTLANGCHANGEREQUEST,	"WM_INPUTLANGCHANGEREQUEST" );
	Insert( WM_INPUTLANGCHANGE, "WM_INPUTLANGCHANGE" );
	Insert( WM_TCARD, "WM_TCARD" );
	Insert( WM_HELP, "WM_HELP" );
	Insert( WM_USERCHANGED, "WM_USERCHANGED" );
	Insert( WM_NOTIFYFORMAT, "WM_NOTIFYFORMAT" );
	Insert( WM_CONTEXTMENU, "WM_CONTEXTMENU" );
	Insert( WM_STYLECHANGING, "WM_STYLECHANGING" );
	Insert( WM_STYLECHANGED, "WM_STYLECHANGED" );
	Insert( WM_DISPLAYCHANGE, "WM_DISPLAYCHANGE" );
	Insert( WM_GETICON, "WM_GETICON" );
	Insert( WM_SETICON, "WM_SETICON" );
	Insert( WM_NCCREATE, "WM_NCCREATE" );
	Insert( WM_NCDESTROY, "WM_NCDESTROY" );
	Insert( WM_NCCALCSIZE, "WM_NCCALCSIZE" );
	Insert( WM_NCHITTEST, "WM_NCHITTEST" );
	Insert( WM_NCPAINT, "WM_NCPAINT" );
	Insert( WM_NCACTIVATE, "WM_NCACTIVATE" );
	Insert( WM_GETDLGCODE, "WM_GETDLGCODE" );
	Insert( WM_SYNCPAINT, "WM_SYNCPAINT" );
	Insert( WM_NCMOUSEMOVE, "WM_NCMOUSEMOVE" );
	Insert( WM_NCLBUTTONDOWN, "WM_NCLBUTTONDOWN" );
	Insert( WM_NCLBUTTONUP, "WM_NCLBUTTONUP" );
	Insert( WM_NCLBUTTONDBLCLK, "WM_NCLBUTTONDBLCLK" );
	Insert( WM_NCRBUTTONDOWN, "WM_NCRBUTTONDOWN" );
	Insert( WM_NCRBUTTONUP, "WM_NCRBUTTONUP" );
	Insert( WM_NCRBUTTONDBLCLK, "WM_NCRBUTTONDBLCLK" );
	Insert( WM_NCMBUTTONDOWN, "WM_NCMBUTTONDOWN" );
	Insert( WM_NCMBUTTONUP, "WM_NCMBUTTONUP" );
	Insert( WM_NCMBUTTONDBLCLK, "WM_NCMBUTTONDBLCLK" );
	Insert( WM_KEYFIRST, "WM_KEYFIRST" );
	Insert( WM_KEYDOWN, "WM_KEYDOWN" );
	Insert( WM_KEYUP, "WM_KEYUP" );
	Insert( WM_CHAR, "WM_CHAR" );
	Insert( WM_DEADCHAR, "WM_DEADCHAR" );
	Insert( WM_SYSKEYDOWN, "WM_SYSKEYDOWN" );
	Insert( WM_SYSKEYUP, "WM_SYSKEYUP" );
	Insert( WM_SYSCHAR, "WM_SYSCHAR" );
	Insert( WM_SYSDEADCHAR, "WM_SYSDEADCHAR" );
	Insert( WM_KEYLAST, "WM_KEYLAST" );
	Insert( WM_IME_STARTCOMPOSITION, "WM_IME_STARTCOMPOSITION" );
	Insert( WM_IME_ENDCOMPOSITION, "WM_IME_ENDCOMPOSITION" );
	Insert( WM_IME_COMPOSITION, "WM_IME_COMPOSITION" );
	Insert( WM_IME_KEYLAST, "WM_IME_KEYLAST" );
	Insert( WM_INITDIALOG, "WM_INITDIALOG" );
	Insert( WM_COMMAND, "WM_COMMAND" );
	Insert( WM_SYSCOMMAND, "WM_SYSCOMMAND" );
	Insert( WM_TIMER, "WM_TIMER" );
	Insert( WM_HSCROLL, "WM_HSCROLL" );
	Insert( WM_VSCROLL, "WM_VSCROLL" );
	Insert( WM_INITMENU, "WM_INITMENU" );
	Insert( WM_INITMENUPOPUP, "WM_INITMENUPOPUP" );
	Insert( WM_MENUSELECT, "WM_MENUSELECT" );
	Insert( WM_MENUCHAR, "WM_MENUCHAR" );
	Insert( WM_ENTERIDLE, "WM_ENTERIDLE" );
	Insert( WM_CTLCOLORMSGBOX, "WM_CTLCOLORMSGBOX" );
	Insert( WM_CTLCOLOREDIT, "WM_CTLCOLOREDIT" );
	Insert( WM_CTLCOLORLISTBOX, "WM_CTLCOLORLISTBOX" );
	Insert( WM_CTLCOLORBTN, "WM_CTLCOLORBTN" );
	Insert( WM_CTLCOLORDLG, "WM_CTLCOLORDLG" );
	Insert( WM_CTLCOLORSCROLLBAR, "WM_CTLCOLORSCROLLBAR" );
	Insert( WM_CTLCOLORSTATIC, "WM_CTLCOLORSTATIC" );
	Insert( WM_MOUSEFIRST, "WM_MOUSEFIRST" );
	Insert( WM_MOUSEMOVE, "WM_MOUSEMOVE" );
	Insert( WM_LBUTTONDOWN, "WM_LBUTTONDOWN" );
	Insert( WM_LBUTTONUP, "WM_LBUTTONUP" );
	Insert( WM_LBUTTONDBLCLK, "WM_LBUTTONDBLCLK" );
	Insert( WM_RBUTTONDOWN, "WM_RBUTTONDOWN" );
	Insert( WM_RBUTTONUP, "WM_RBUTTONUP" );
	Insert( WM_RBUTTONDBLCLK, "WM_RBUTTONDBLCLK" );
	Insert( WM_MBUTTONDOWN, "WM_MBUTTONDOWN" );
	Insert( WM_MBUTTONUP, "WM_MBUTTONUP" );
	Insert( WM_MBUTTONDBLCLK, "WM_MBUTTONDBLCLK" );
	Insert( WM_MOUSELAST, "WM_MOUSELAST" );
	Insert( WM_PARENTNOTIFY, "WM_PARENTNOTIFY" );
	Insert( WM_ENTERMENULOOP, "WM_ENTERMENULOOP" );
	Insert( WM_EXITMENULOOP, "WM_EXITMENULOOP" );
	Insert( WM_NEXTMENU, "WM_NEXTMENU" );
	Insert( WM_SIZING, "WM_SIZING" );
	Insert( WM_CAPTURECHANGED, "WM_CAPTURECHANGED" );
	Insert( WM_MOVING, "WM_MOVING" );
	Insert( WM_POWERBROADCAST, "WM_POWERBROADCAST" );
	Insert( WM_DEVICECHANGE, "WM_DEVICECHANGE" );
	Insert( WM_MDICREATE, "WM_MDICREATE" );
	Insert( WM_MDIDESTROY, "WM_MDIDESTROY" );
	Insert( WM_MDIACTIVATE, "WM_MDIACTIVATE" );
	Insert( WM_MDIRESTORE, "WM_MDIRESTORE" );
	Insert( WM_MDINEXT, "WM_MDINEXT" );
	Insert( WM_MDIMAXIMIZE, "WM_MDIMAXIMIZE" );
	Insert( WM_MDITILE, "WM_MDITILE" );
	Insert( WM_MDICASCADE, "WM_MDICASCADE" );
	Insert( WM_MDIICONARRANGE, "WM_MDIICONARRANGE" );
	Insert( WM_MDIGETACTIVE, "WM_MDIGETACTIVE" );
	Insert( WM_MDISETMENU, "WM_MDISETMENU" );
	Insert( WM_ENTERSIZEMOVE, "WM_ENTERSIZEMOVE" );
	Insert( WM_EXITSIZEMOVE, "WM_EXITSIZEMOVE" );
	Insert( WM_DROPFILES, "WM_DROPFILES" );
	Insert( WM_MDIREFRESHMENU, "WM_MDIREFRESHMENU" );
	Insert( WM_IME_SETCONTEXT, "WM_IME_SETCONTEXT" );
	Insert( WM_IME_NOTIFY, "WM_IME_NOTIFY" );
	Insert( WM_IME_CONTROL, "WM_IME_CONTROL" );
	Insert( WM_IME_COMPOSITIONFULL, "WM_IME_COMPOSITIONFULL" );
	Insert( WM_IME_SELECT, "WM_IME_SELECT" );
	Insert( WM_IME_CHAR, "WM_IME_CHAR" );
	Insert( WM_IME_KEYDOWN, "WM_IME_KEYDOWN" );
	Insert( WM_IME_KEYUP, "WM_IME_KEYUP" );
	Insert( WM_CUT, "WM_CUT" );
	Insert( WM_COPY, "WM_COPY" );
	Insert( WM_PASTE, "WM_PASTE" );
	Insert( WM_CLEAR, "WM_CLEAR" );
	Insert( WM_UNDO, "WM_UNDO" );
	Insert( WM_RENDERFORMAT, "WM_RENDERFORMAT" );
	Insert( WM_RENDERALLFORMATS, "WM_RENDERALLFORMATS" );
	Insert( WM_DESTROYCLIPBOARD, "WM_DESTROYCLIPBOARD" );
	Insert( WM_DRAWCLIPBOARD, "WM_DRAWCLIPBOARD" );
	Insert( WM_PAINTCLIPBOARD, "WM_PAINTCLIPBOARD" );
	Insert( WM_VSCROLLCLIPBOARD, "WM_VSCROLLCLIPBOARD" );
	Insert( WM_SIZECLIPBOARD, "WM_SIZECLIPBOARD" );
	Insert( WM_ASKCBFORMATNAME, "WM_ASKCBFORMATNAME" );
	Insert( WM_CHANGECBCHAIN, "WM_CHANGECBCHAIN" );
	Insert( WM_HSCROLLCLIPBOARD, "WM_HSCROLLCLIPBOARD" );
	Insert( WM_QUERYNEWPALETTE, "WM_QUERYNEWPALETTE" );
	Insert( WM_PALETTEISCHANGING, "WM_PALETTEISCHANGING" );
	Insert( WM_PALETTECHANGED, "WM_PALETTECHANGED" );
	Insert( WM_HOTKEY, "WM_HOTKEY" );
	Insert( WM_PRINT, "WM_PRINT" );
	Insert( WM_PRINTCLIENT, "WM_PRINTCLIENT" );
	Insert( WM_HANDHELDFIRST, "WM_HANDHELDFIRST" );
	Insert( WM_HANDHELDLAST, "WM_HANDHELDLAST" );
	Insert( WM_AFXFIRST, "WM_AFXFIRST" );
	Insert( WM_AFXLAST, "WM_AFXLAST" );
	Insert( WM_PENWINFIRST, "WM_PENWINFIRST" );
	Insert( WM_PENWINLAST, "WM_PENWINLAST" );
	Insert( WM_APP, "WM_APP" );
	Insert( WM_USER, "WM_USER" );
	Insert( WM_MOUSEWHEEL, "WM_MOUSEWHEEL" );

	//Insert( WM_CTLCOLOR, "WM_CTLCOLOR" );
	//Insert( WM_GETOBJECT, "WM_GETOBJECT" );
	//Insert( WM_MENURBUTTONUP, "WM_MENURBUTTONUP" );
	//Insert( WM_MENUDRAG, "WM_MENUDRAG" );
	//Insert( WM_MENUGETOBJECT, "WM_MENUGETOBJECT" );
	//Insert( WM_UNINITMENUPOPUP, "WM_UNINITMENUPOPUP" );
	//Insert( WM_MENUCOMMAND, "WM_MENUCOMMAND" );
	//Insert( WM_IME_REQUEST, "WM_IME_REQUEST" );
	//Insert( WM_MOUSEHOVER, "WM_MOUSEHOVER" );
	//Insert( WM_MOUSELEAVE, "WM_MOUSELEAVE" );
}


string CWMMnemonicCodes::Get( UINT nMessage )
{
	string szMnemonic = GetMnemonic( nMessage );
	szMnemonic += StrFmt( "( 0x%X( %u ) )", nMessage, nMessage );
	if ( szMnemonic.empty() )
	{
		if ( nMessage < WM_USER )
		{
			return StrFmt( "UNKNOWN( 0x%X( %u ) )", nMessage, nMessage );
		}
		else
		{
			return StrFmt( "UNKNOWN( 0x%X( %u ) ): WM_USER( 0x%X ) + ( 0x%X( %u ) )", nMessage, nMessage, WM_USER, nMessage - WM_USER, nMessage - WM_USER );
		}
	}
	return szMnemonic;
}

// basement storage  


