#pragma once
#include "Resources.h"

// The editor's icon strips -- tree_types.bmp, pc_types.bmp and their headers --
// for wx.
//
// Each strip is a row of 16 pixel icons in one bitmap, with magenta for the
// transparent pixels, which MFC made into a CImageList with
// CImageList::Add( &bmp, RGB( 255, 0, 255 ) ).
//
// The bitmaps are generated byte tables rather than PE resources now, and each
// one is a whole .bmp file, so wx's own reader decodes it and the round trip
// through LoadImage, GetObject and GetDIBits that used to be here is gone with
// the last of the Win32 in this header.


#include <wx/bitmap.h>
#include <wx/image.h>
#include <wx/log.h>
#include <wx/mstream.h>

#include <vector>

namespace NWxResourceImages
{
	// The bitmap nResourceID names, with no mask set; an invalid image when
	// there is no such bitmap or it will not decode. Every read of one goes
	// through here.
	inline wxImage ReadBitmapResource( unsigned nResourceID )
	{
		const unsigned char *pData = nullptr;
		size_t nSize = 0;
		if ( !NResources::GetBinaryResource( nResourceID, &pData, &nSize ) )
		{
			return wxImage();
		}
		wxMemoryInputStream stream( pData, nSize );
		// Quietly: wx puts a dialog up for an image it cannot read, and every
		// caller here already answers with an empty image.
		wxLogNull noLog;
		wxImage image;
		if ( !image.LoadFile( stream, wxBITMAP_TYPE_BMP ) )
		{
			return wxImage();
		}
		return image;
	}


	// A row of 16 pixel icons, magenta made transparent: the editor's own icon
	// strips are drawn that way.
	inline wxImage LoadStrip( unsigned nResourceID )
	{
		wxImage strip = ReadBitmapResource( nResourceID );
		if ( strip.IsOk() )
		{
			strip.SetMaskColour( 255, 0, 255 );
		}
		return strip;
	}


	// The strip cut into its nSize pixel icons, left to right; empty when it
	// cannot be read.
	inline std::vector<wxBitmap> LoadIcons( unsigned nResourceID, int nSize = 16 )
	{
		std::vector<wxBitmap> icons;
		const wxImage strip = LoadStrip( nResourceID );
		if ( !strip.IsOk() )
		{
			return icons;
		}
		for ( int nX = 0; nX + nSize <= strip.GetWidth(); nX += nSize )
		{
			icons.push_back( wxBitmap( strip.GetSubImage( wxRect( nX, 0, nSize, ( std::min )( nSize, strip.GetHeight() ) ) ) ) );
		}
		return icons;
	}
}

