function(add_unit_test filename)
    add_executable(${filename}_test EXCLUDE_FROM_ALL ${filename}.cpp)
    target_link_libraries(${filename}_test PRIVATE GTest::gtest_main 3Dmotor Misc)
    gtest_discover_tests(${filename}_test)
    set_target_properties(${filename}_test PROPERTIES FOLDER "unittest")
endfunction()

add_unit_test(MultiplyOnColor)
add_unit_test(CalcDirectionalLighting)
add_unit_test(MMXhelpers)
