basestruct int;
basestruct float;
basestruct bool;
basestruct string;
basestruct wstring;
basestruct hexbinary;
basestruct GUID;
basestruct uint32_t;
baseclass void;

attribute unsafe( bool );
attribute hidden( bool );
attribute private( bool );
attribute readonly( bool );
attribute noKey( bool );
attribute noCode( bool );
attribute noHeader( bool );
attribute useUpperType( bool );
attribute noBase( bool );
attribute deprecated( bool );
attribute typeRename( string );
attribute typePrefix( string );
attribute editorControl( string );
attribute key();
attribute stringParam( string );
attribute minInclusive( int );
attribute maxInclusive( int );
attribute numBytes( int );
attribute intParam( int );
attribute section( string );
attribute typeID( hexbinary );
attribute chunkID( int );
attribute rndType( string );

