#pragma once

enum ESceneObjAnimMode
{
	OBJ_ANIM_MODE_DEFAULT,
	OBJ_ANIM_MODE_FORCE_NON_ANIMATED,
	OBJ_ANIM_MODE_FORCE_ANIMATED,
	OBJ_ANIM_MODE_FORCE_ANIMATED_STATIC,
	OBJ_ANIM_MODE_FORCE_ANIMATED_STATIC_ABS, // absolute timer
};

