#pragma once

#include "System/Dg.h"

enum ESceneMode : int
{
	SCENE_MODE_CONFIG,
	SCENE_MODE_FULLSCREEN,
	SCENE_MODE_WINDOWED,
};

enum EScene : int
{
	SCENE_MISSION = 0,
	SCENE_2D,							// loading screens etc.
	ES_UNKNOWN = 3
};

enum
{
	OBJECT_ID_GENERATE	= -1,
	OBJECT_ID_FORGET		= 0,
};

enum ESceneShow : int
{
	SCENE_SHOW_BBOXES,
	SCENE_SHOW_GRID,
	SCENE_SHOW_WIREFRAME,
	SCENE_SHOW_MIPMAPS,
	SCENE_SHOW_OVERDRAW,
	SCENE_SHOW_UI,
	SCENE_SHOW_STATISTICS,
	SCENE_SHOW_AI_GRID,
	SCENE_SHOW_TERRAIN,
	SCENE_SHOW_SHADOWS,
	SCENE_SHOW_NO_FLIP,
	SCENE_SHOW_AI_GEOM,
	SCENE_SHOW_PASS_MARKERS
};

enum ESceneMarkerType : int
{
	ESMT_SHOOT_AREA,
	ESMT_LINE,
	ESMT_KEY_AREA,
	_ESMT_ENUM_COUNTER,
};

DEFINE_DG_CONSTANT_NODE( CCSTime, NTimer::STime );

