project(MapEditor)
set(SOURCES
    AboutDialog.cpp
    BinaryBitFieldDialog.cpp
    BuilderContainer.cpp
    ChildFrameContainer.cpp
    ComboBox_GDBBrowser.cpp
    CommandHandlerContainer.cpp
    ControllerContainer.cpp
    CreateMODDialog.cpp
    DefaultChildFrame.cpp
    DefaultDockingWindow.cpp
    DW_GDBBrowser.cpp
    DW_LayerBrowser.cpp
    DW_Log.cpp
    DW_PropertyBrowser.cpp
    EditorContainer.cpp
    Empty_GDBBrowser.cpp
    ExporterContainer.cpp
    FindTextDlg.cpp
    FolderCallback.cpp
    LogWindow.cpp
    LuaEditor.cpp
    MainFrame.cpp
    MainFrameContainer.cpp
    MainFrameParams.cpp
    MainFrame_Consts.cpp
    MapEditorApp.cpp
    MapEditorSingleton.cpp
    MDDLDialog.cpp
    MODContainer.cpp
    NewObjectDialog.cpp
    ObjectCollector.cpp
    OpenMODDialog.cpp
    PC_BaseDialog.cpp
    PC_BinaryBitFieldEditor.cpp
    PC_BoolCheckBoxEditor.cpp
    PC_BoolComboEditor.cpp
    PC_BoolSwitcherEditor.cpp
    PC_BuildDataDialog.cpp
    PC_DBLinkDialog.cpp
    PC_Dialog.cpp
    PC_EditorButton.cpp
    PC_EditorSlider.cpp
    PC_ExTextFileEditor.cpp
    PC_FloatComboEditor.cpp
    PC_FloatInputEditor.cpp
    PC_FloatSliderEditor.cpp
    PC_GUIDEditor.cpp
    PC_IntColorEditor.cpp
    PC_IntComboEditor.cpp
    PC_IntInputEditor.cpp
    PC_IntSliderEditor.cpp
    PC_ItemEditor.cpp
    PC_MainTreeControl.cpp
    PC_MultilineStringEditor.cpp
    PC_String3ButtonEditor.cpp
    PC_StringBigInputEditor.cpp
    PC_StringBrowseEditor.cpp
    PC_StringComboEditor.cpp
    PC_StringComboRefEditor.cpp
    PC_StringDirRefEditor.cpp
    PC_StringFileRefEditor.cpp
    PC_StringInputEditor.cpp
    PC_StringMultibuttonEditor.cpp
    PC_StringNewBrowseEditor.cpp
    PC_StringNewRefEditor.cpp
    PC_StringRefEditor.cpp
    PC_StringSliderEditor.cpp
    PC_TextFileEditor.cpp
    PC_Vec3ColorEditor.cpp
    ProgressDialog.cpp
    ProgressDlg.cpp
    ProgressHook.cpp
    ProgressThread.cpp
    RefListDialog.cpp
    RefListWaitDialog.cpp
    RegisterEditors.cpp
    ReplaceTextDlg.cpp
    ScriptEditor.cpp
    SearchObjectDialog.cpp
    SelectTablesDialog.cpp
    SortTreeControl.cpp
    stdafx.cpp
    TextEditorDialog.cpp
    Tree_GDBBrowser.cpp
    Tree_GDBBrowserBase.cpp
    Tree_GDBBrowser_InputState.cpp
    Tree_GDBLinkBrowser.cpp
    UserDataContainer.cpp
    ViewContainer.cpp
)
add_library(MapEditor SHARED ${SOURCES})
add_stdafx_pch(MapEditor)
add_export_header(MapEditor)
target_link_libraries(MapEditor PRIVATE 3DLib 3Dmotor ED_Common Input libdb Main MapEditorLib MemoryLib Misc Scintilla Script stingray System fmt::fmt-header-only)
if(WIN32)
    target_link_libraries(MapEditor PRIVATE Htmlhelp winapi)
endif()
install(TARGETS MapEditor DESTINATION bin)
add_version_info(MapEditor)
