// Generated from MapEditor.rc by scripts/port/rc2strings.py.
//
// The editor's string table, which was a Win32 STRINGTABLE until the PE
// resource section stopped being available on every platform the editor
// builds for. This file is the source now: the .rc block it came from is
// gone, and a new string is added here.
//
// The ids are the macros, not their numbers, so ResourceDefines.h stays the one
// place that says what a number means.

#include "stdafx.h"

#include "ResourceDefines.h"
#include "MapEditorLib/Resources.h"

namespace
{
	const NResources::SStringEntry ENTRIES[] =
	{
		{ IDR_EDITORTYPE,                              "IDR_EDITORTYPE" },
		{ IDR_MAINFRAME,                               "IDR_MAINFRAME" },
		{ IDS_TOOLBAR_CUSTOMIZE_COMMAND,               "Command" },
		{ IDS_TOOLBAR_MENU,                            "Menu" },
		{ IDS_TOOLBAR_MAIN,                            "File Toolbar" },
		{ IDS_TOOLBAR_SELECTION,                       "Edit Toolbar" },
		{ IDS_TOOLBAR_CONTROLLER_CONTAINER,            "Undo / Redo Operation Toolbar" },
		{ IDS_TOOLBAR_OBJECT,                          "Object Toolbar" },
		{ IDS_TOOLBAR_PROPERTY_CONTROL,                "Property Control Toolbar" },
		{ IDS_TOOLBAR_VIEW,                            "View Toolbar" },
		{ IDS_DW_GDB_BROWSE_NAME,                      "Game Database Window %d" },
		{ IDS_DW_PROPERTY_BROWSE_NAME,                 "Selection Properties" },
		{ IDS_DW_LOG_NAME,                             "Log Window" },
		{ IDS_PROGRAM_VERSION,                         "1.0" },
		{ IDS_HELP_FILE_NAME,                          "MapEditor.chm" },
		{ IDS_NO_HELP_FILE_MESSAGE,                    "Can't find <%s> help file." },
		{ IDS_BROWSE_FOR_FOLDER_DIALOG_TITLE,          "Browse for folder: %s" },
		{ IDS_BROWSE_FOR_FILE_DIALOG_TITLE,            "Browse for file: %s" },
		{ AFX_IDS_APP_TITLE,                           "Common Editor" },
		{ AFX_IDS_IDLEMESSAGE,                         "Ready" },
		{ IDS_REGISTRY_PATH,                           "Nival Interactive" },
		{ IDS_REGISTRY_KEY,                            "Params" },
		{ IDS_REGISTRY_KEY_MAXIMIZE,                   "Maximize" },
		{ IDS_REGISTRY_KEY_RECT,                       "Rect" },
		{ IDS_REGISTRY_KEY_VERSION,                    "Version" },
		{ IDS_REGISTRY_KEY_RECENT_LIST,                "List" },
		{ IDS_REGISTRY_KEY_TABLE,                      "Table" },
		{ IDS_REGISTRY_CURRENT_TABLE,                  "CurrentTable" },
		{ IDS_REGISTRY_KEY_TOOLBAR,                    "Toolbars" },
		{ IDS_REGISTRY_KEY_WINDOWBAR,                  "Windows" },
		{ IDS_TREE_GDB_BROWSE_NEW_FOLDER,              "New Folder" },
		{ IDS_TREE_GDB_BROWSE_NEW_RESOURCE,            "New Object" },
		{ IDS_TREE_GDB_BROWSE_NEW_MAIN_OBJECT,         "New Map" },
		{ IDS_TREE_GDB_BROWSE_DELETE_OBJECTS_MESSAGE,  "Are you sure you want to delete these objects?" },
		{ IDS_TREE_GDB_BROWSE_NO_OBJECT_FOUND_MESSAGE, "Search is complete.\r\nThere are no %s objects to display." },
		{ IDS_TREE_GDB_BROWSE_CFM,                     "All unreferenced objects in active table will be deleted.\r\nAre you sure you want to delete all unreferenced objects?" },
		{ IDS_TREE_GDB_BROWSE_CFM_OBJECT_FOUND,        "%d unreferenced object was deleted." },
		{ IDS_TREE_GDB_BROWSE_CFM_OBJECTS_FOUND,       "%d unreferenced objects were deleted." },
		{ IDS_TREE_GDB_BROWSE_CFM_NO_OBJECT_FOUND,     "No unreferenced objects found." },
		{ IDS_TREE_GDB_BROWSE_LOAD,                    "Edit &Selection" },
		{ IDS_TREE_GDB_LINK_BROWSE_SELECT,             "&Select" },
		{ IDS_TREE_GDB_BROWSE_CHECK_WARNING,           "You have chosen hierarchical check. This operation can take several minutes.\r\nContinue?" },
		{ IDS_TREE_GDB_BROWSE_EXPORT_WARNING,          "You have chosen hierarchical export. This operation can take several minutes.\r\nContinue?" },
		{ IDS_TREE_GDB_BROWSE_EXPORT_FORCE_WARNING,    "You have chosen forced hierarchical export. This operation can take several minutes.\r\nContinue?" },
		{ IDS_PC_PROPERTY_THN_0,                       "Property" },
		{ IDS_PC_PROPERTY_THN_1,                       "Value" },
		{ IDS_PC_PROPERTY_THN_2,                       "Description" },
		{ IDS_PC_DELETE_MESSAGE,                       "Are you sure you want to delete selected elements?" },
		{ IDS_PC_DELETE_ALL_MESSAGE,                   "Are you sure you want to delete all elements?" },
		{ IDS_TABGDBB_PROPERTY_THN_0,                  "Name" },
		{ IDS_TABGDBB_PROPERTY_THN_1,                  "ID" },
		{ IDS_PM_CREATE_EDITOR,                        "Open resource %s..." },
		{ IDS_PM_DESTROY_EDITOR,                       "Close active editor..." },
		{ IDS_PM_RELOAD_EDITOR,                        "Reload active editor..." },
		{ IDS_PM_SAVE,                                 "Save resources..." },
		{ IDS_PM_REDO,                                 "Redo changes..." },
		{ IDS_PM_UNDO,                                 "Undo changes..." },
		{ IDS_PM_CREATE_MOD,                           "Create MOD: %s..." },
		{ IDS_PM_OPEN_MOD,                             "Open MOD: %s..." },
		{ IDS_PM_CLOSE_MOD,                            "Close MOD: %s..." },
		{ ID_VIEW_TOOLBAR_MAIN,                        "Toggle ( show or hide ) the Main toolbar\nMain Toolbar" },
		{ ID_VIEW_TOOLBAR_CONTROLLER_CONTAINER,        "Toggle ( show or hide ) the Undo / Redo toolbar\nUndo / Redo Toolbar" },
		{ ID_VIEW_TOOLBAR_SELECTION,                   "Toggle ( show or hide ) the Edit toolbar\nEdit Toolbar" },
		{ ID_VIEW_TOOLBAR_OBJECT,                      "nToggle ( show or hide ) the Object toolbar\nObject Toolbar" },
		{ ID_VIEW_TOOLBAR_PROPERTY_CONTROL,            "Toggle ( show or hide ) the Property Control toolbar\nPoperty Control Toolbar" },
		{ ID_VIEW_TOOLBAR_VIEW,                        "Toggle ( show or hide ) the View toolbar\nView  Toolbar" },
		{ ID_VIEW_DW_PROPERTY_BROWSER,                 "Toggle ( show or hide ) the Selection Property window\nSelection Property Window" },
		{ ID_VIEW_DW_LOG,                              "Toggle ( show or hide ) the Log window\nLog Window" },
		{ ID_VIEW_DW_GDB_BROWSER_FIRST,                "Toggle ( show or hide ) the Game Database window\nGame Database Window" },
		{ ID_VIEW_RESET_GUI,                           "Restore default panels and toolbars\nReset GUI" },
		{ ID_TOOLS_CUSTOMIZE,                          "Customize toolbars\nCustomize" },
		{ ID_HELP_CONTENTS,                            "Help Topics\nContents" },
		{ ID_HELP_ABOUT,                               "Display program information, version number and copyright\nAbout" },
		{ ID_APP_EXIT,                                 "Quit the Map Editor\nExit" },
		{ IDS_PC_BD_DIALOG_TITLE,                      "Create New <%s> Object" },
		{ IDS_PC_OPEN_DIALOG_EMPTY_TITLE,              "Open Object" },
		{ IDS_PC_OPEN_DIALOG_TITLE,                    "Open <%s> Object" },
		{ IDS_PC_LINK_DIALOG_EMPTY_TITLE,              "Browse Object Link" },
		{ IDS_PC_LINK_DIALOG_TITLE,                    "Browse <%s> Object Link" },
		{ IDS_RECENT_EMPTY,                            "No Recent List Entries" },
		{ IDS_DW_GDB_BROWSE_MENU_LABEL,                "Game Database Window &%d\tCtrl+Shift+B" },
		{ IDS_DW_GDB_BROWSE_MENU_LABEL_SHORT,          "Game Database Window &%d" },
		{ IDS_DW_GDB_BROWSE_EMPTY_MENU_LABEL,          "No Game Database Windows" },
		{ IDS_PC_LUA_EDITOR_TITLE,                     "Script Editor" },
		{ IDS_PC_TXT_EDITOR_TITLE,                     "Text Editor" },
		{ IDS_REF_LIST_NO_ITEMS,                       "No references were found" },
		{ IDS_REF_LIST_SET_EMPTY_FAILURE,              "Nullification of some references have failed." },
		{ IDS_REF_LIST_EMPTY_ALL_LONG_TIME_WARNING,    "This is a very lengthy operation. The application may not respond for a long time.\nDo you really want to continue?" },
		{ ID_MAIN_NEW,                                 "Create new map\nNew" },
		{ ID_MAIN_OPEN,                                "Open existing map\nOpen" },
		{ ID_MAIN_CLOSE,                               "Close active editor\nClose" },
		{ ID_MAIN_NEW_RESOURCE,                        "Create new game resource\nNew resource" },
		{ ID_MAIN_OPEN_RESOURCE,                       "Open existing game resource\nOpen resource" },
		{ ID_MAIN_SAVE,                                "Save all unsaved data\nSave All" },
		{ ID_MAIN_RELOAD,                              "Refresh active tables\nRefresh Tables" },
		{ ID_MAIN_REGISTER_XDB,                        "Register an existing XDB in the current game or mod database\nRegister XDB" },
		{ ID_TOOLS_RUN_GAME,                           "Save and start the open map in Game.exe\nStart Mission in Game" },
		{ ID_MAIN_SELECT,                              "Select active tables\nSelect Tables" },
		{ ID_MAIN_RECENT_0,                            "Open this map\nOpen" },
		{ ID_MAIN_RECENT_1,                            "Open this map\nOpen" },
		{ ID_MAIN_RECENT_2,                            "Open this map\nOpen" },
		{ ID_MAIN_RECENT_3,                            "Open this map\nOpen" },
		{ ID_MAIN_RECENT_4,                            "Open this map\nOpen" },
		{ ID_MAIN_RECENT_5,                            "Open this map\nOpen" },
		{ ID_MAIN_RECENT_6,                            "Open this map\nOpen" },
		{ ID_MAIN_RECENT_7,                            "Open this map\nOpen" },
		{ ID_MAIN_RECENT_8,                            "Open this map\nOpen" },
		{ ID_MAIN_RECENT_9,                            "Open this map\nOpen" },
		{ ID_MAIN_RECENT_RESOURCE_0,                   "Open this game resource\nOpen resource" },
		{ ID_MAIN_RECENT_RESOURCE_1,                   "Open this game resource\nOpen resource" },
		{ ID_MAIN_RECENT_RESOURCE_2,                   "Open this game resource\nOpen resource" },
		{ ID_MAIN_RECENT_RESOURCE_3,                   "Open this game resource\nOpen resource" },
		{ ID_MAIN_RECENT_RESOURCE_4,                   "Open this game resource\nOpen resource" },
		{ ID_MAIN_RECENT_RESOURCE_5,                   "Open this game resource\nOpen resource" },
		{ ID_MAIN_RECENT_RESOURCE_6,                   "Open this game resource\nOpen resource" },
		{ ID_MAIN_RECENT_RESOURCE_7,                   "Open this game resource\nOpen resource" },
		{ ID_MAIN_RECENT_RESOURCE_8,                   "Open this game resource\nOpen resource" },
		{ ID_MAIN_RECENT_RESOURCE_9,                   "Open this game resource\nOpen resource" },
		{ ID_MAIN_GETLATEST,                           "Get latest database\nGet Latest" },
		{ ID_MAIN_CHECKOUT,                            "Check out database\nCheck Out" },
		{ ID_MAIN_CHECKIN,                             "Check it database\nCheck In" },
		{ ID_MAIN_OBJECT_LOCATE,                       "Show resource properties\nProperties" },
		{ ID_SELECTION_CUT,                            "Cut selection and put it on the Clipboard\nCut" },
		{ ID_SELECTION_COPY,                           "Copy the selection and put it on the Clipboard\nCopy" },
		{ ID_SELECTION_PASTE,                          "Insert Clipboard contents\nPaste" },
		{ ID_SELECTION_RENAME,                         "Rename the selection\nRename" },
		{ ID_SELECTION_CLEAR,                          "Erase the selection\nDelete" },
		{ ID_SELECTION_SELECT_ALL,                     "Select the entire document\nSelect All" },
		{ ID_SELECTION_FIND,                           "Find the specified element\n Find" },
		{ ID_CC_UNDO,                                  "Undo the last action\nUndo" },
		{ ID_CC_REDO,                                  "Redo the previously undone action\nRedo" },
		{ ID_CC_UNDO_ARROW,                            "Undo the last action\nUndo" },
		{ ID_CC_REDO_ARROW,                            "Redo the previously undone action\nRedo" },
		{ ID_OBJECT_LOAD,                              "Open selected game resource\nSelect" },
		{ ID_OBJECT_NEW_FOLDER,                        "Create new folder\nNew Folder" },
		{ ID_OBJECT_NEW,                               "Create new game resource\nNew Object" },
		{ ID_OBJECT_NEW_FOLDER_AT_ROOT,                "Create new root folder\nNew Root Folder" },
		{ ID_OBJECT_NEW_AT_ROOT,                       "Create new root game resource\nNew Root Object" },
		{ ID_OBJECT_CHECK,                             "Check selected game resources\nCheck" },
		{ ID_OBJECT_EXPORT,                            "Export selected game rosources\nExport" },
		{ ID_OBJECT_EXPORT_FORCE,                      "Force export selected game resources\nForce Export" },
		{ ID_OBJECT_EXPORT_NO_REF,                     "Export selected game resources without export referenced resources\nExport Selection Only" },
		{ ID_OBJECT_EXPORT_NO_REF_FORCE,               "Force export selected game resources without export referenced resources\nForce Export Selection Only" },
		{ ID_OBJECT_COLOR,                             "Change selection color\nColor" },
		{ ID_OBJECT_REF_LOOKUP,                        "Find All game resources who references on selection\nList &References" },
		{ ID_PC_EXPAND_ALL,                            "Expand all nodes\nExpand All Nodes" },
		{ ID_PC_EXPAND,                                "Expand focused node\nExpand Node" },
		{ ID_PC_COLLAPSE,                              "Collapse focused node\nCollapse Node" },
		{ ID_PC_COLLAPSE_ALL,                          "Collapse all nodes\nCollapse All Nodes" },
		{ ID_PC_OPTIMAL_WIDTH,                         "Set optimal width\nSet Optimal Width" },
		{ ID_PC_REFRESH,                               "Refresh selecton from base\nRefresh" },
		{ ID_PC_ADD_NODE,                              "Add node\nAdd Node" },
		{ ID_PC_DELETE_ALL_NODES,                      "Delete all nodes\nDelete All Nodes" },
		{ ID_PC_INSERT_NODE,                           "Insert node to focused position\nInsert Node" },
		{ ID_PC_DELETE_NODE,                           "Delete focused node\nDelete Node" },
		{ ID_PC_SHOW_HIDDEN,                           "Show hidden nodes\nShow Hidden" },
		{ ID_TE_SAVE,                                  "Save\nSave" },
		{ ID_TE_CLOSE,                                 "Close\nClose" },
		{ ID_LOG_SHOW_MESSAGES,                        "Show messages\nShow Messages" },
		{ ID_LOG_SHOW_WARNINGS,                        "Show warnings\nShow Warnings" },
		{ ID_LOG_SHOW_ERRORS,                          "Show errors\nShow Errors" },
		{ IDS_CONFIRM_SAVE_MESSAGE_SHORT,              "Do you want save changes?" },
		{ IDS_CONFIRM_SAVE_MESSAGE_LONG,               "Do you want save changes in %s?" },
		{ IDS_BROWSE_BUTTON_TITLE,                     "..." },
		{ IDS_NEW_BUTTON_TITLE,                        "New" },
		{ IDS_EDIT_BUTTON_TITLE,                       "Edit" },
	};

	// Registered before main runs, like the resource section was mapped
	// before it. Order between modules is load order, which is the order
	// the executable's resources used to be searched in.
	const NResources::CStringTable TABLE( ENTRIES, sizeof( ENTRIES ) / sizeof( ENTRIES[0] ) );
}
