#include "StdAfx.h"
#include <crtdbg.h>
#include "../libdb/ObjMan.h"
#include "../libdb/ObjManIterator.h"
#include "../libdb/TypeDef.h"
#include "MeasureTimer.h"

namespace NTest
{
struct SIteratorTestData
{
	bool bHidden;
	string szFieldName;
	int nType;
	string szTypeName;
};
static SIteratorTestData mainTestData[] = 
{
	{ false, "Name", 6, "wstring" },
	{ false, "HP", 2, "float" },
	{ false, "HasPassability", 3, "bool" },
	{ false, "Flags", 7, "Flags" },
	{ false, "DesignerName", 5, "string" },
	{ false, "UnitType", 8, "UnitType" },
	{ false, "Sight", 2, "float" },
	{ false, "Speed", 2, "float" },
	{ false, "BoundTileRadius", 1, "int" },
	{ false, "Jx", 11, "Jogging" },
	{ false, "Jx.Amplitude", 2, "float" },
	{ false, "Jx.Phase", 2, "float" },
	{ false, "Jx.Shift", 2, "float" },
	{ false, "Jx.Tremble", 11, "Vec3" },
	{ false, "Jx.Tremble.x", 2, "float" },
	{ false, "Jx.Tremble.y", 2, "float" },
	{ false, "Jx.Tremble.z", 2, "float" },
	{ false, "Jy", 11, "Jogging" },
	{ false, "Jy.Amplitude", 2, "float" },
	{ false, "Jy.Phase", 2, "float" },
	{ false, "Jy.Shift", 2, "float" },
	{ false, "Jy.Tremble", 11, "Vec3" },
	{ false, "Jy.Tremble.x", 2, "float" },
	{ false, "Jy.Tremble.y", 2, "float" },
	{ false, "Jy.Tremble.z", 2, "float" },
	{ false, "guid", 4, "GUID" },
	{ false, "nocodeInt", 1, "int" },
	{ false, "nocodeFloat", 2, "float" },
	{ false, "nocodeBool", 3, "bool" },
	{ false, "nocodeString", 5, "string" },
	{ false, "nocodeWString", 6, "wstring" },
	{ false, "nocodeGUID", 4, "GUID" },
	{ false, "nocodeEnumUnitType", 8, "UnitType" },
	{ false, "nocodeBinaryFlags", 7, "Flags" },
	{ false, "SimpleArrayInt", 10, "array" },
	{ false, "SimpleArrayInt.[0]", 1, "int" },
	{ false, "SimpleArrayInt.[1]", 1, "int" },
	{ false, "SimpleArrayInt.[2]", 1, "int" },
	{ false, "SimpleArrayInt.[3]", 1, "int" },
	{ false, "SimpleArrayInt.[4]", 1, "int" },
	{ false, "SimpleArrayFloat", 10, "array" },
	{ false, "SimpleArrayFloat.[0]", 2, "float" },
	{ false, "SimpleArrayFloat.[1]", 2, "float" },
	{ false, "SimpleArrayFloat.[2]", 2, "float" },
	{ false, "SimpleArrayFloat.[3]", 2, "float" },
	{ false, "SimpleArrayFloat.[4]", 2, "float" },
	{ false, "SimpleArrayGUID", 10, "array" },
	{ false, "SimpleArrayGUID.[0]", 4, "GUID" },
	{ false, "SimpleArrayGUID.[1]", 4, "GUID" },
	{ false, "SimpleArrayGUID.[2]", 4, "GUID" },
	{ false, "SimpleArrayGUID.[3]", 4, "GUID" },
	{ false, "SimpleArrayGUID.[4]", 4, "GUID" },
	{ false, "SimpleArrayBinaryFlags", 10, "array" },
	{ false, "SimpleArrayBinaryFlags.[0]", 7, "Flags" },
	{ false, "SimpleArrayBinaryFlags.[1]", 7, "Flags" },
	{ false, "SimpleArrayBinaryFlags.[2]", 7, "Flags" },
	{ false, "SimpleArrayBinaryFlags.[3]", 7, "Flags" },
	{ false, "SimpleArrayBinaryFlags.[4]", 7, "Flags" },
	{ false, "SimpleArrayEnumUnitType", 10, "array" },
	{ false, "SimpleArrayEnumUnitType.[0]", 8, "UnitType" },
	{ false, "SimpleArrayEnumUnitType.[1]", 8, "UnitType" },
	{ false, "SimpleArrayEnumUnitType.[2]", 8, "UnitType" },
	{ false, "SimpleArrayEnumUnitType.[3]", 8, "UnitType" },
	{ false, "SimpleArrayEnumUnitType.[4]", 8, "UnitType" },
	{ false, "SimpleArrayString", 10, "array" },
	{ false, "SimpleArrayString.[0]", 5, "string" },
	{ false, "SimpleArrayString.[1]", 5, "string" },
	{ false, "SimpleArrayString.[2]", 5, "string" },
	{ false, "SimpleArrayString.[3]", 5, "string" },
	{ false, "SimpleArrayString.[4]", 5, "string" },
	{ false, "SimpleArrayWString", 10, "array" },
	{ false, "SimpleArrayWString.[0]", 6, "wstring" },
	{ false, "SimpleArrayWString.[1]", 6, "wstring" },
	{ false, "SimpleArrayWString.[2]", 6, "wstring" },
	{ false, "SimpleArrayWString.[3]", 6, "wstring" },
	{ false, "SimpleArrayWString.[4]", 6, "wstring" },
	{ false, "SimpleArrayIntNocode", 10, "array" },
	{ false, "SimpleArrayIntNocode.[0]", 1, "int" },
	{ false, "SimpleArrayIntNocode.[1]", 1, "int" },
	{ false, "SimpleArrayIntNocode.[2]", 1, "int" },
	{ false, "SimpleArrayIntNocode.[3]", 1, "int" },
	{ false, "SimpleArrayIntNocode.[4]", 1, "int" },
	{ false, "SimpleArrayFloatNocode", 10, "array" },
	{ false, "SimpleArrayFloatNocode.[0]", 2, "float" },
	{ false, "SimpleArrayFloatNocode.[1]", 2, "float" },
	{ false, "SimpleArrayFloatNocode.[2]", 2, "float" },
	{ false, "SimpleArrayFloatNocode.[3]", 2, "float" },
	{ false, "SimpleArrayFloatNocode.[4]", 2, "float" },
	{ false, "SimpleArrayGUIDNocode", 10, "array" },
	{ false, "SimpleArrayGUIDNocode.[0]", 4, "GUID" },
	{ false, "SimpleArrayGUIDNocode.[1]", 4, "GUID" },
	{ false, "SimpleArrayGUIDNocode.[2]", 4, "GUID" },
	{ false, "SimpleArrayGUIDNocode.[3]", 4, "GUID" },
	{ false, "SimpleArrayGUIDNocode.[4]", 4, "GUID" },
	{ false, "SimpleArrayBinaryFlagsNocode", 10, "array" },
	{ false, "SimpleArrayBinaryFlagsNocode.[0]", 7, "Flags" },
	{ false, "SimpleArrayBinaryFlagsNocode.[1]", 7, "Flags" },
	{ false, "SimpleArrayBinaryFlagsNocode.[2]", 7, "Flags" },
	{ false, "SimpleArrayBinaryFlagsNocode.[3]", 7, "Flags" },
	{ false, "SimpleArrayBinaryFlagsNocode.[4]", 7, "Flags" },
	{ false, "SimpleArrayEnumUnitTypeNocode", 10, "array" },
	{ false, "SimpleArrayEnumUnitTypeNocode.[0]", 8, "UnitType" },
	{ false, "SimpleArrayEnumUnitTypeNocode.[1]", 8, "UnitType" },
	{ false, "SimpleArrayEnumUnitTypeNocode.[2]", 8, "UnitType" },
	{ false, "SimpleArrayEnumUnitTypeNocode.[3]", 8, "UnitType" },
	{ false, "SimpleArrayEnumUnitTypeNocode.[4]", 8, "UnitType" },
	{ false, "SimpleArrayStringNocode", 10, "array" },
	{ false, "SimpleArrayStringNocode.[0]", 5, "string" },
	{ false, "SimpleArrayStringNocode.[1]", 5, "string" },
	{ false, "SimpleArrayStringNocode.[2]", 5, "string" },
	{ false, "SimpleArrayStringNocode.[3]", 5, "string" },
	{ false, "SimpleArrayStringNocode.[4]", 5, "string" },
	{ false, "SimpleArrayWStringNocode", 10, "array" },
	{ false, "SimpleArrayWStringNocode.[0]", 6, "wstring" },
	{ false, "SimpleArrayWStringNocode.[1]", 6, "wstring" },
	{ false, "SimpleArrayWStringNocode.[2]", 6, "wstring" },
	{ false, "SimpleArrayWStringNocode.[3]", 6, "wstring" },
	{ false, "SimpleArrayWStringNocode.[4]", 6, "wstring" },
	{ false, "ComplexArrayStruct1", 10, "array" },
	{ false, "ComplexArrayStruct1.[0]", 11, "Struct1" },
	{ false, "ComplexArrayStruct1.[0].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct1.[0].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct1.[0].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct1.[0].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct1.[0].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct1.[0].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct1.[0].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct1.[0].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct1.[1]", 11, "Struct1" },
	{ false, "ComplexArrayStruct1.[1].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct1.[1].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct1.[1].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct1.[1].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct1.[1].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct1.[1].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct1.[1].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct1.[1].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct1.[2]", 11, "Struct1" },
	{ false, "ComplexArrayStruct1.[2].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct1.[2].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct1.[2].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct1.[2].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct1.[2].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct1.[2].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct1.[2].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct1.[2].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct1.[3]", 11, "Struct1" },
	{ false, "ComplexArrayStruct1.[3].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct1.[3].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct1.[3].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct1.[3].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct1.[3].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct1.[3].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct1.[3].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct1.[3].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct1.[4]", 11, "Struct1" },
	{ false, "ComplexArrayStruct1.[4].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct1.[4].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct1.[4].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct1.[4].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct1.[4].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct1.[4].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct1.[4].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct1.[4].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2", 10, "array" },
	{ false, "ComplexArrayStruct2.[0]", 11, "Struct2" },
	{ false, "ComplexArrayStruct2.[0].Structs", 10, "array" },
	{ false, "ComplexArrayStruct2.[0].Structs.[0]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[0].Structs.[0].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[0].Structs.[0].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[0].Structs.[0].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[0].Structs.[0].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[0].Structs.[0].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[0].Structs.[0].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[0].Structs.[0].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[0].Structs.[0].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[0].Structs.[1]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[0].Structs.[1].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[0].Structs.[1].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[0].Structs.[1].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[0].Structs.[1].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[0].Structs.[1].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[0].Structs.[1].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[0].Structs.[1].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[0].Structs.[1].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[0].Structs.[2]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[0].Structs.[2].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[0].Structs.[2].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[0].Structs.[2].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[0].Structs.[2].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[0].Structs.[2].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[0].Structs.[2].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[0].Structs.[2].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[0].Structs.[2].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[0].Structs.[3]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[0].Structs.[3].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[0].Structs.[3].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[0].Structs.[3].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[0].Structs.[3].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[0].Structs.[3].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[0].Structs.[3].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[0].Structs.[3].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[0].Structs.[3].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[0].Structs.[4]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[0].Structs.[4].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[0].Structs.[4].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[0].Structs.[4].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[0].Structs.[4].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[0].Structs.[4].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[0].Structs.[4].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[0].Structs.[4].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[0].Structs.[4].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[0].guids", 10, "array" },
	{ false, "ComplexArrayStruct2.[0].guids.[0]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[0].guids.[1]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[0].guids.[2]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[0].guids.[3]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[0].guids.[4]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[1]", 11, "Struct2" },
	{ false, "ComplexArrayStruct2.[1].Structs", 10, "array" },
	{ false, "ComplexArrayStruct2.[1].Structs.[0]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[1].Structs.[0].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[1].Structs.[0].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[1].Structs.[0].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[1].Structs.[0].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[1].Structs.[0].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[1].Structs.[0].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[1].Structs.[0].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[1].Structs.[0].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[1].Structs.[1]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[1].Structs.[1].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[1].Structs.[1].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[1].Structs.[1].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[1].Structs.[1].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[1].Structs.[1].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[1].Structs.[1].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[1].Structs.[1].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[1].Structs.[1].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[1].Structs.[2]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[1].Structs.[2].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[1].Structs.[2].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[1].Structs.[2].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[1].Structs.[2].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[1].Structs.[2].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[1].Structs.[2].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[1].Structs.[2].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[1].Structs.[2].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[1].Structs.[3]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[1].Structs.[3].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[1].Structs.[3].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[1].Structs.[3].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[1].Structs.[3].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[1].Structs.[3].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[1].Structs.[3].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[1].Structs.[3].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[1].Structs.[3].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[1].Structs.[4]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[1].Structs.[4].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[1].Structs.[4].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[1].Structs.[4].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[1].Structs.[4].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[1].Structs.[4].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[1].Structs.[4].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[1].Structs.[4].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[1].Structs.[4].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[1].guids", 10, "array" },
	{ false, "ComplexArrayStruct2.[1].guids.[0]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[1].guids.[1]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[1].guids.[2]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[1].guids.[3]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[1].guids.[4]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[2]", 11, "Struct2" },
	{ false, "ComplexArrayStruct2.[2].Structs", 10, "array" },
	{ false, "ComplexArrayStruct2.[2].Structs.[0]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[2].Structs.[0].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[2].Structs.[0].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[2].Structs.[0].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[2].Structs.[0].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[2].Structs.[0].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[2].Structs.[0].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[2].Structs.[0].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[2].Structs.[0].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[2].Structs.[1]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[2].Structs.[1].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[2].Structs.[1].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[2].Structs.[1].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[2].Structs.[1].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[2].Structs.[1].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[2].Structs.[1].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[2].Structs.[1].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[2].Structs.[1].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[2].Structs.[2]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[2].Structs.[2].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[2].Structs.[2].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[2].Structs.[2].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[2].Structs.[2].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[2].Structs.[2].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[2].Structs.[2].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[2].Structs.[2].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[2].Structs.[2].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[2].Structs.[3]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[2].Structs.[3].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[2].Structs.[3].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[2].Structs.[3].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[2].Structs.[3].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[2].Structs.[3].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[2].Structs.[3].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[2].Structs.[3].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[2].Structs.[3].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[2].Structs.[4]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[2].Structs.[4].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[2].Structs.[4].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[2].Structs.[4].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[2].Structs.[4].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[2].Structs.[4].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[2].Structs.[4].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[2].Structs.[4].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[2].Structs.[4].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[2].guids", 10, "array" },
	{ false, "ComplexArrayStruct2.[2].guids.[0]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[2].guids.[1]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[2].guids.[2]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[2].guids.[3]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[2].guids.[4]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[3]", 11, "Struct2" },
	{ false, "ComplexArrayStruct2.[3].Structs", 10, "array" },
	{ false, "ComplexArrayStruct2.[3].Structs.[0]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[3].Structs.[0].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[3].Structs.[0].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[3].Structs.[0].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[3].Structs.[0].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[3].Structs.[0].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[3].Structs.[0].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[3].Structs.[0].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[3].Structs.[0].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[3].Structs.[1]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[3].Structs.[1].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[3].Structs.[1].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[3].Structs.[1].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[3].Structs.[1].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[3].Structs.[1].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[3].Structs.[1].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[3].Structs.[1].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[3].Structs.[1].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[3].Structs.[2]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[3].Structs.[2].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[3].Structs.[2].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[3].Structs.[2].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[3].Structs.[2].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[3].Structs.[2].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[3].Structs.[2].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[3].Structs.[2].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[3].Structs.[2].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[3].Structs.[3]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[3].Structs.[3].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[3].Structs.[3].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[3].Structs.[3].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[3].Structs.[3].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[3].Structs.[3].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[3].Structs.[3].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[3].Structs.[3].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[3].Structs.[3].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[3].Structs.[4]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[3].Structs.[4].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[3].Structs.[4].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[3].Structs.[4].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[3].Structs.[4].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[3].Structs.[4].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[3].Structs.[4].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[3].Structs.[4].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[3].Structs.[4].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[3].guids", 10, "array" },
	{ false, "ComplexArrayStruct2.[3].guids.[0]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[3].guids.[1]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[3].guids.[2]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[3].guids.[3]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[3].guids.[4]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[4]", 11, "Struct2" },
	{ false, "ComplexArrayStruct2.[4].Structs", 10, "array" },
	{ false, "ComplexArrayStruct2.[4].Structs.[0]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[4].Structs.[0].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[4].Structs.[0].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[4].Structs.[0].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[4].Structs.[0].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[4].Structs.[0].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[4].Structs.[0].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[4].Structs.[0].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[4].Structs.[0].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[4].Structs.[1]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[4].Structs.[1].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[4].Structs.[1].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[4].Structs.[1].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[4].Structs.[1].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[4].Structs.[1].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[4].Structs.[1].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[4].Structs.[1].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[4].Structs.[1].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[4].Structs.[2]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[4].Structs.[2].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[4].Structs.[2].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[4].Structs.[2].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[4].Structs.[2].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[4].Structs.[2].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[4].Structs.[2].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[4].Structs.[2].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[4].Structs.[2].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[4].Structs.[3]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[4].Structs.[3].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[4].Structs.[3].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[4].Structs.[3].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[4].Structs.[3].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[4].Structs.[3].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[4].Structs.[3].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[4].Structs.[3].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[4].Structs.[3].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[4].Structs.[4]", 11, "Struct1" },
	{ false, "ComplexArrayStruct2.[4].Structs.[4].TypeInt", 1, "int" },
	{ true , "ComplexArrayStruct2.[4].Structs.[4].TypeFloat", 2, "float" },
	{ false, "ComplexArrayStruct2.[4].Structs.[4].TypeBool", 3, "bool" },
	{ true , "ComplexArrayStruct2.[4].Structs.[4].TypeGUID", 4, "GUID" },
	{ true , "ComplexArrayStruct2.[4].Structs.[4].TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[4].Structs.[4].TypeWString", 6, "wstring" },
	{ false, "ComplexArrayStruct2.[4].Structs.[4].TypeEnumUnitType", 8, "UnitType" },
	{ false, "ComplexArrayStruct2.[4].Structs.[4].TypeBinaryFlags", 7, "Flags" },
	{ false, "ComplexArrayStruct2.[4].guids", 10, "array" },
	{ false, "ComplexArrayStruct2.[4].guids.[0]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[4].guids.[1]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[4].guids.[2]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[4].guids.[3]", 4, "GUID" },
	{ false, "ComplexArrayStruct2.[4].guids.[4]", 4, "GUID" },
	{ false, "Weapon", 9, "ref" },
	{ false, "Weapons", 10, "array" },
	{ false, "", -1, "" }
};
//
static SIteratorTestData elementTestData[] = 
{
	{ false, "TypeInt", 1, "int" },
	{ true , "TypeFloat", 2, "float" },
	{ false, "TypeBool", 3, "bool" },
	{ true , "TypeGUID", 4, "GUID" },
	{ true , "TypeString", 5, "string" },
	{ false, "TypeWString", 6, "wstring" },
	{ false, "TypeEnumUnitType", 8, "UnitType" },
	{ false, "TypeBinaryFlags", 7, "Flags" },
	{ false, "", -1, "" }
};

bool TestMainIterator( NDb::IObjMan *pObjMan, SIteratorTestData *pTestData, const char *pszTestName, bool bShowHidden )
{
	CMeasureTimer timer( pszTestName );
	int i = 0;
	for ( CObj<NDb::IObjManIterator> pIterator = pObjMan->CreateIterator(bShowHidden); !pIterator->IsEnd(); pIterator->Next(), ++i )
	{
		while ( !bShowHidden && pTestData[i].bHidden )
			++i;
		// check field's name
		const string szFieldName = pIterator->GetName();
//		const NDb::NTypeDef::STypeStructBase::SField *pField = pIterator->GetDesc();
//		const char *pszHidden = pField->HasAttribute("hidden") == true ? "true " : "false";
//		DebugTrace( "{ %s, \"%s\", %d, \"%s\" },", pszHidden, szFieldName.c_str(), pField->pType->eType, pField->pType->GetTypeName() );

		NI_VERIFY( szFieldName == pTestData[i].szFieldName, 
			StrFmt("Mismatch in field's name: \"%s\" != \"%s\" for %d test element", szFieldName.c_str(), pTestData[i].szFieldName.c_str(), i),
			return false );
		// check field's type and type name
		const NDb::NTypeDef::STypeStructBase::SField *pField = pIterator->GetDesc();
		NI_VERIFY( pField->pType->eType == pTestData[i].nType, 
			StrFmt("Mismatch in field's type: %d != %d for %d test element", pField->pType->eType, pTestData[i].nType, i),
			return false );
		NI_VERIFY( pTestData[i].szTypeName == pField->pType->GetTypeName(),
			StrFmt("Mismatch in field's type name: \"%s\" != \"%s\" for %d test element", pField->pType->GetTypeName(), pTestData[i].szTypeName.c_str(), i),
			return false );
	}
	return true;
}

//
struct SDirectPropGetData
{
	bool bValid;
	string szFieldName;
	int nType;
	string szTypeName;
};
static const SDirectPropGetData directPropGetMainData[] = 
{
	{ true , "ComplexArrayStruct2.[2].Structs.[4].TypeBinaryFlags", 7, "Flags" },
	{ true , "ComplexArrayStruct2.[2].Structs.[4]", 11, "Struct1" },
	{ true , "ComplexArrayStruct2.[2].Structs", 10, "array" },
	{ true , "ComplexArrayStruct2.[2]", 11, "Struct2" },
	{ true , "ComplexArrayStruct2", 10, "array" },
	{ false, "ComplexArrayStruct2.[2].Str", 0, "" },
	{ false, "", -1, "" }
};
static const SDirectPropGetData directPropGetMaskData[] = 
{
	{ true , "TypeBinaryFlags", 7, "Flags" },
	{ true , "TypeString", 5, "string" },
	{ false, "ComplexArrayStruct2.[2].Structs", 10, "array" },
	{ false, "ComplexArrayStruct2.[2]", 11, "Struct2" },
	{ false, "ComplexArrayStruct2", 10, "array" },
	{ false, "ComplexArrayStruct2.[2].Str", 0, "" },
	{ false, "", -1, "" }
};
bool TestDirectGetProp( NDb::IObjMan *pObjMan, const SDirectPropGetData *pData, const char *pszTestName )
{
	CMeasureTimer timer( pszTestName );
	for ( const SDirectPropGetData *pCurr = pData; pCurr->nType != -1; ++pCurr )
	{
		const NDb::NTypeDef::STypeStructBase::SField *pField = pObjMan->GetDesc( pCurr->szFieldName );
		NI_VERIFY( (pCurr->bValid && pField != 0) || (!pCurr->bValid && pField == 0), StrFmt("Direct property get \"%s\" failed", pCurr->szFieldName.c_str()), return false );
		if ( pField == 0 )
			continue;
		//
		NI_VERIFY( pField->pType->eType == pCurr->nType && pField->pType->GetTypeName() == pCurr->szTypeName, StrFmt("Incorrent direct property \"%s\"", pCurr->szFieldName.c_str()), return false );
	}
	return true;
}

bool TestIterator( NDb::IObjMan *pObjMan )
{
	// main manipulator iterator
	NI_VERIFY( TestMainIterator(pObjMan, mainTestData, "Main Iterator", false) != false, "Main iterator test has failed", return false );
	NI_ASSERT( _CrtCheckMemory() == TRUE, "Memory check failed!" );
	NI_VERIFY( TestMainIterator(pObjMan, mainTestData, "Main Iterator (show hidden)", true) != false, "Main iterator test (show hidden) has failed", return false );
	NI_ASSERT( _CrtCheckMemory() == TRUE, "Memory check failed!" );
	// mask manipulator iterator
	CObj<NDb::IObjMan> pArrayMan = pObjMan->CreateManipulator( "ComplexArrayStruct2.[2].Structs.[3]" );
	NI_VERIFY( pArrayMan != 0, "Failed to create array element manipulator during iterator test", return false );
	NI_VERIFY( TestMainIterator(pArrayMan, elementTestData, "Array Element Iterator", false) != false, "Array element iterator test has failed", return false );
	NI_ASSERT( _CrtCheckMemory() == TRUE, "Memory check failed!" );
	NI_VERIFY( TestMainIterator(pArrayMan, elementTestData, "Array Element Iterator (show hidden)", true) != false, "Array element iterator test (show hidden) has failed", return false );
	NI_ASSERT( _CrtCheckMemory() == TRUE, "Memory check failed!" );
	// direct gets: main
	NI_VERIFY( TestDirectGetProp(pObjMan, directPropGetMainData, "Direct prop get (main)") != false, "Direct prop get failed for main manipulator", return false );
	NI_ASSERT( _CrtCheckMemory() == TRUE, "Memory check failed!" );
	// direct gets: mask
	NI_VERIFY( TestDirectGetProp(pArrayMan, directPropGetMaskData, "Direct prop get (mask)") != false, "Direct prop get failed for mask manipulator", return false );
	NI_ASSERT( _CrtCheckMemory() == TRUE, "Memory check failed!" );
	//
	return true;
}

}