#pragma once

#include "Stats_B2_M1/AckTypes.h"

struct SAckDebugHelper
{
	NDb::EUnitAckType eAckType;
	const char* pszName;
};

static SAckDebugHelper debugAckNames[] = 
{
	{ NDb::ACK_BORED_ATTACK, "ACK_BORED_ATTACK" },
	{ NDb::ACK_BORED_IDLE, "ACK_BORED_IDLE" },
	{ NDb::ACK_BUILDING_FINISHED, "ACK_BUILDING_FINISHED" },
	{ NDb::ACK_CANNOT_FINISH_BUILD, "ACK_CANNOT_FINISH_BUILD" },
	{ NDb::ACK_CANNOT_MOVE_TRACK_DAMAGED, "ACK_CANNOT_MOVE_TRACK_DAMAGED" },
	{ NDb::ACK_CANNOT_PIERCE, "ACK_CANNOT_PIERCE" },
	{ NDb::ACK_DONT_SEE_THE_ENEMY, "ACK_DONT_SEE_THE_ENEMY" },
	{ NDb::ACK_GOING_TO_STORAGE, "ACK_GOING_TO_STORAGE" },
	{ NDb::ACK_INVALID_TARGET, "ACK_INVALID_TARGET" },
	{ NDb::ACK_KILLED_ENEMY, "ACK_KILLED_ENEMY" },
	{ NDb::ACK_NEGATIVE, "ACK_NEGATIVE" },
	{ NDb::ACK_NEGATIVE_NOTIFICATION, "ACK_NEGATIVE_NOTIFICATION" },
	{ NDb::ACK_NO_AMMO, "ACK_NO_AMMO" },
	{ NDb::ACK_NO_RESOURCES_CANT_FIND_DEPOT, "ACK_NO_RESOURCES_CANT_FIND_DEPOT" },
	{ NDb::ACK_NOT_IN_ATTACK_ANGLE, "ACK_NOT_IN_ATTACK_ANGLE" },
	{ NDb::ACK_NOT_IN_FIRE_RANGE, "ACK_NOT_IN_FIRE_RANGE" },
	{ NDb::ACK_PLANE_LEAVING, "ACK_PLANE_LEAVING" },
	{ NDb::ACK_PLANE_REACH_POINT_START_ATTACK, "ACK_PLANE_REACH_POINT_START_ATTACK" },
	{ NDb::ACK_POSITIVE, "ACK_POSITIVE" },
	{ NDb::ACK_SELECTED, "ACK_SELECTED" },
	{ NDb::ACK_SELECTION_TO_MUCH, "ACK_SELECTION_TO_MUCH" },
	{ NDb::ACK_START_SERVICE_REPAIR, "ACK_START_SERVICE_REPAIR" },
	{ NDb::ACK_START_SERVICE_RESUPPLY, "ACK_START_SERVICE_RESUPPLY" },
	{ NDb::ACK_UNIT_DIED, "ACK_UNIT_DIED" },
	{ NDb::ACK_MOVE_END, "ACK_MOVE_END" },
	{ NDb::ACK_UNDER_ATTACK, "ACK_UNDER_ATTACK" },
	{ NDb::ACK_ENEMY_FOUND, "ACK_ENEMY_FOUND" },
	{ NDb::ACK_ORDER_FINISHED, "ACK_ORDER_FINISHED" },
	{ NDb::ACK_REINFORCEMENT_ARRIVED, "ACK_REINFORCEMENT_ARRIVED" },
	{ NDb::ACK_MINE_FOUND, "ACK_MINE_FOUND" },
	{ NDb::ACK_START_SERVICE_BUILDING, "ACK_START_SERVICE_BUILDING" },
	{ NDb::ACK_LOW_AMMO, "ACK_LOW_AMMO" },
	{ NDb::ACK_LOW_HIT_POINTS, "ACK_LOW_HIT_POINTS" },
	{ NDb::ACK_CANNOT_FIND_PATH_TO_TARGET, "ACK_CANNOT_FIND_PATH_TO_TARGET" },
	{ NDb::ACK_NOT_TRACEABLE, "ACK_NOT_TRACEABLE" },
	{ NDb::ACK_PLANE_TAKING_OFF, "ACK_PLANE_TAKING_OFF" },

	{ NDb::ACK_NONE, "ACK_NONE" },
};


