project(GameX)
set(SOURCES
    AICmdsAutoMagic.cpp
    AILogicCommandInternal.cpp
    CameraMovement.cpp
    CampaignSelectionMenu.cpp
    CClientGameConsts.cpp
    ChatControl.cpp
    CommandsHistory.cpp
    CommandsSender.cpp
    CommonCommands.cpp
    CustomMissions.cpp
    DBConsts.cpp
    dbgameoptions.cpp
    DBGameRoot.cpp
    DBMPConsts.cpp
    DBScenario.cpp
    DBWrapReinf.cpp
    DummyInterface.cpp
    FontChars.cpp
    FontData.cpp
    FontInfo.cpp
    GameRoomData.cpp
    Initialization.cpp
    InterfaceArmyBranchDlg.cpp
    InterfaceArmyScreen.cpp
    InterfaceChapterMapMenu.cpp
    InterfaceChapterMapMenuDialogs.cpp
    InterfaceChapterMapMenuHelper.cpp
    InterfaceChapterMapMenuInit.cpp
    InterfaceChapterMapMenuReinfDesc.cpp
    InterfaceCredits.cpp
    InterfaceCustomCampaign.cpp
    InterfaceCustomMissions.cpp
    InterfaceDemo.cpp
    InterfaceEncyclopedia.cpp
    InterfaceEscMenu.cpp
    InterfaceHallOfFame.cpp
    InterfaceHelp.cpp
    InterfaceLoadingSingle.cpp
    InterfaceLoadMod.cpp
    InterfaceMainMenu.cpp
    InterfaceMisc.cpp
    InterfaceMissionBackground.cpp
    InterfaceMissionBase.cpp
    InterfaceMissionBriefing.cpp
    InterfaceMissionInternal.cpp
    InterfaceMissionMovieBorder.cpp
    InterfaceMissionObjectives.cpp
    InterfaceMPBase.cpp
    InterfaceMPCreateCustomGame.cpp
    InterfaceMPCustomGame.cpp
    InterfaceMPGameRoom.cpp
    InterfaceMPLadderGame.cpp
    InterfaceMPLadderStatistics.cpp
    InterfaceMPLoading.cpp
    InterfaceMPLobby.cpp
    InterfaceMPLobbyChat.cpp
    InterfaceMPStatistics.cpp
    InterfaceMPWaitPlayers.cpp
    InterfaceMultiplayer.cpp
    InterfaceNivalNet.cpp
    InterfaceNotifications.cpp
    InterfaceOptionsMenu.cpp
    InterfacePlayerStats.cpp
    InterfaceReplaySaveLoad.cpp
    InterfaceSaveLoadMenu.cpp
    InterfaceScreenBase.cpp
    InterfaceSelectTutorial.cpp
    InterfaceSingleStatistic.cpp
    InterfaceStateInternal.cpp
    InterfaceTestScreen.cpp
    InterfaceWinLoose.cpp
    MapSizeSorter.cpp
    MissionReinforcements.cpp
    MissionUnitFullInfo.cpp
    MissionWarFog.cpp
    MODSetup.cpp
    MouseTranslator.cpp
    MPInterfaceData.cpp
    MPLANTest.cpp
    MPLobbyData.cpp
    MPManager.cpp
    MPManagerMode.cpp
    MPManagerModeClients.cpp
    MPManagerModeGameControl.cpp
    MPManagerModeLAN.cpp
    MPManagerModeMessages.cpp
    MPManagerModeNivalNet.cpp
    MPManagerModeNivalNetChat.cpp
    MPManagerModePackets.cpp
    MPTransceiver.cpp
    MultiplayerCommandProcessor.cpp
    MultiplayerNetPackets.cpp
    MultiplayerTestNet.cpp
    PlayMovieInterface.cpp
    ProfileManagerMenu.cpp
    SaveLoadHelper.cpp
    ScenarioTracker.cpp
    ScenarioTrackerMP.cpp
    Selector.cpp
    SinglePlayerTransceiver.cpp
    stdafx.cpp
    SuperWeapon.cpp
    UIElementsHelper.cpp
    UnitFullInfoHelper.cpp
    Utils.cpp
    WorldClient.cpp
    WorldClientActions.cpp
)
include(GenerateExportHeader)
add_library(GameX SHARED ${SOURCES})
generate_export_header(GameX EXPORT_FILE_NAME ${CMAKE_CURRENT_SOURCE_DIR}/GameX_export.h)
target_link_libraries(GameX PRIVATE 3Dmotor AILogic B2_M1_World Client Common_RTS_AI DebugTools Image Input libdb Main MemoryLib Misc Net SceneB2 Script Server_Client_Common Sound Stats_B2_M1 System UISpecificB2 UI zlib)
install(TARGETS GameX DESTINATION bin)
