#include "stdafx.h"

#include "CommonPackets.h"
#include "CustomLobbyPackets.h"
#include "LadderLobbyPackets.h"
#include "GamePackets.h"
#include "LoginPackets.h"
#include "ZipPacket.h"

#include "Server_Client_Common_export.h"

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 1, CLoginPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 2, CRegisterPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 3, CCheckConnectPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 4, CCheckConnectAnswerPacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 5, CConnectGamePacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 6, CAnswerConnectGame );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 7, CNewGameConnectingClient );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 8, CGameConnectingClientAccepted );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 9, CConnectGameFailed );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 10, CWant2Connect2Client );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 11, CClientGameConnectInfo );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 12, CClientWantToConnect );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 13, CGameClientRemoved );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 14, CIndentityPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 15, CNewGameClient );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 16, CGameKilled );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 17, CZipPacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 18, CLeaveGamePacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 19, CUpdateGameInfo );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 20, CLobbyGamesPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 21, CCustomLobbyClientsPacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 22, CNetNewClient );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 23, CNetRemoveClient );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 24, CConnectServerPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 25, CEnterLobbyPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 26, CLeaveLobbyPacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 27, CChatPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 28, CChatAFKPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 29, CChatAFKResponsePacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 30, CCommonClientStatePacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 31, CMyIDPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 32, CGetLobbyClientsPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 33, CGameHeartBeatPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 34, CKillGamePacket )
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 35, CGetLobbyGamesPacket )
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 36, CCreateGamePacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 37, CConnectedGameID );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 38, CGameKickClient );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 39, CGameClientWasKicked );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 40, CDirectPacketToClient );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 41, CTestDirectPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 42, CSpecificGameInfo );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 43, CThroughServerConnectionPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 44, CGameClientDead );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 45, CThroughServerGamePacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 46, CGameTestBroadcastMsg );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 47, CGameTestDirectMsg );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 48, CPingPacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 49, CLadderInfoPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 50, CLadderGameResultPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 51, CLadderInvitePacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 52, CLadderStatisticsRequestPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 53, CLadderStatisticsPacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 54, CChatChannelPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 55, CChatChannelClientsListPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 56, CChatClientListChangeNotifyPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 57, CChatChannelsListRequestPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 58, CChatChannelsListPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 59, CChatModifyIgnoreFriendListPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 60, CChatIgnoreFriendListPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 61, CChatGetIgnoreFriendListPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 62, CChatChannelByNickPacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 63, CForgottenPasswordPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 64, CForgottenPasswordAnswerPacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 65, CSystemBroadcastPacket );
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 66, CChatFriendNotifyPacket );

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 67, CGameStartLoadingPacket )
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 69, CLadderShortStatisticsPacket )
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 70, CLadderSurrenderPacket )
REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 71, CLadderInvalidStatisticsPacket )

// For too smart linker
void ForcePacketRegistration()
{
	static int nForcePackerRegistration = 0;
	++nForcePackerRegistration;
}

REGISTER_SAVELOAD_CLASS( SERVER_CLIENT_COMMON, 0x19245C01, SGameInfo );

