project(ED_B2_M1)
set(SOURCES
    AckExcelReader.cpp
    AckSetBuilder.cpp
    AdvClipboardState.cpp
    AdvClipboardWindow.cpp
    AIGeneralState.cpp
    AIGeneralTypes.cpp
    AIGeneralWindow.cpp
    AIGenMobileIDDlg.cpp
    AIGenParcelDlg.cpp
    aiObject.cpp
    AnimationBuilder.cpp
    AnimationExporter.cpp
    AnimationMnemonics.cpp
    BridgeInfoData.cpp
    BridgeRPGStatsExporter.cpp
    BridgeState.cpp
    BuilderMethods.cpp
    BuildingEditor.cpp
    BuildingInterface.cpp
    BuildingRPGStatsBuilder.cpp
    BuildingRPGStatsExporter.cpp
    BuildingState.cpp
    CameraPositionState.cpp
    CameraPositionWindow.cpp
    CampaignExporter.cpp
    CFC_SceneB2.cpp
    CF_SceneB2.cpp
    ChapterExporter.cpp
    ClientGameConstsExporter.cpp
    CoastState.cpp
    CragState.cpp
    dbadvclipboard.cpp
    dbbuildersb2.cpp
    dbeditoroptionsb2.cpp
    DBField.cpp
    DBMinimap.cpp
    DrawToolsDC.cpp
    DynamicDebrisSetBuilder.cpp
    EditorInterfaceBase.cpp
    EditorMethods.cpp
    EditorOptions.cpp
    EditorScene.cpp
    editortest.cpp
    EditorTestEditor.cpp
    EditorTestInterface.cpp
    EditorTestState.cpp
    EditorUpdatableWorld.cpp
    EdUnitStartCmd.cpp
    ED_B2_M1Dll.cpp
    EffectEditor.cpp
    EffectInterface.cpp
    EffectState.cpp
    EnterNameDialog.cpp
    EntrenchmentExporter.cpp
    EntrenchmentInfoData.cpp
    EntrenchmentMnemonics.cpp
    EntrenchmentState.cpp
    ExporterMethods.cpp
    FenceRPGStatsExporter.cpp
    FenceState.cpp
    FieldState.cpp
    FieldWindow.cpp
    FormationMnemonics.cpp
    FormationsState.cpp
    FormationWindow.cpp
    GameRootExporter.cpp
    GeometryExporter.cpp
    HeightContainer.cpp
    HeightPattern.cpp
    HeightStateV3.cpp
    HeightWindowV3.cpp
    HPObjectRPGStatsExporter.cpp
    IconsCreation.cpp
    InfantryRPGStatsBuilder.cpp
    KeySettingsDlg.cpp
    LakeState.cpp
    LightExporter.cpp
    MapClip.cpp
    MapInfoAIMarkersSelectDlg.cpp
    MapInfoBuilder.cpp
    MapInfoController.cpp
    MapInfoEditor.cpp
    MapInfoEditorData.cpp
    MapInfoEditorData_Clipboard.cpp
    MapInfoEditorData_Consts.cpp
    MapInfoEditorData_ObjectInfo.cpp
    MapInfoEditorData_ObjectInfoCollector.cpp
    MapInfoEditorData_Selection.cpp
    MapInfoEditorSettings.cpp
    MapInfoExporter.cpp
    MapInfoInterface.cpp
    MapInfoState.cpp
    MapInfoStoreInputState.cpp
    MapInfoViewFilterDlg.cpp
    MapObjectDataExtractor.cpp
    MapObjectMultiState.cpp
    MapObjectState.cpp
    MapObjectWindow.cpp
    MarkerSet.cpp
    MechUnitRPGStatsBuilder.cpp
    MechUnitRPGStatsExporter.cpp
    MinimapExporter.cpp
    MinimapImage.cpp
    MinimapMnemonics.cpp
    MiniMapWindow.cpp
    MiniMap_ImageCreation.cpp
    ModelEditor.cpp
    ModelEditorSettings.cpp
    ModelExporter.cpp
    ModelInterface.cpp
    ModelState.cpp
    ModelWindow.cpp
    MovEditorSettingsWindow.cpp
    MoviesEditorData.cpp
    MoviesEditorWindow.cpp
    MusicTrackExporter.cpp
    ObjectBaseRPGStatsExporter.cpp
    ObjectRPGStatsBuilder.cpp
    ObjectRPGStatsExporter.cpp
    PassabilityProfile.cpp
    PointListDialog.cpp
    PointsListState.cpp
    PolygonState.cpp
    ReinforcementTypes.cpp
    ReinfPointsState.cpp
    ReinfPointsTypedDlg.cpp
    ReinfPointsTypedTemplateAddDlg.cpp
    ReinfPointsWindow.cpp
    RiverState.cpp
    RoadState.cpp
    ScriptAreaState.cpp
    ScriptAreaWindow.cpp
    ScriptCameraAddDlg.cpp
    ScriptCameraEditorData.cpp
    ScriptCameraMovementTypes.cpp
    ScriptCameraRun.cpp
    ScriptCameraState.cpp
    ScriptCameraWindow.cpp
    SeasonMnemonics.cpp
    SimpleObjectInfoData.cpp
    SimpleObjectState.cpp
    SkeletonExporter.cpp
    SoundDescExporter.cpp
    SpotDataExtractor.cpp
    SpotInfoData.cpp
    SpotState.cpp
    SquadEditor.cpp
    SquadExporter.cpp
    SquadInterface.cpp
    SquadState.cpp
    StaticDebrisSetBuilder.cpp
    StaticObjectRPGStatsExporter.cpp
    stdafx.cpp
    TargetMesh.cpp
    TerrainEditor.cpp
    TerrainInterface.cpp
    TerrainState.cpp
    TGNoiseExporter.cpp
    TileDataExtractor.cpp
    TimeSliderControl.cpp
    Tools_SceneDraw.cpp
    Tools_SceneGeometry.cpp
    TraceModel.cpp
    UIScene.cpp
    UnitAnimationExporter.cpp
    UnitDesignTypes.cpp
    UnitStartCmdState.cpp
    UnitStartCmdWindow.cpp
    VisObjBuilder.cpp
    VSODataExtractor.cpp
    VSOManager.cpp
    VSOMultiState.cpp
    VSOState.cpp
    VSOStateEx.cpp
    VSOWindow.cpp
    WeaponMnemonics.cpp
    XMLExport.cpp
    XMLExportB2.cpp
)
add_library(ED_B2_M1 SHARED ${SOURCES})
add_stdafx_pch(ED_B2_M1)
add_export_header(ED_B2_M1)
target_link_libraries(ED_B2_M1 PRIVATE 3DLib 3Dmotor B2_M1_Terrain B2_M1_World ED_Common Image Input libdb Main MapEditorLib MemoryLib Misc SceneB2 Scintilla Stats_B2_M1 stingray System UISpecificB2 UI zlib)
if(WIN32)
    target_link_libraries(ED_B2_M1 PRIVATE winapi)
endif()
install(TARGETS ED_B2_M1 DESTINATION bin)
add_version_info(ED_B2_M1)
