#include "stdafx.h"
#include "Misc/2Darray.h"
#include "Stats_B2_M1/RPGStats.h"
#include "ReinforcementTypes.h"

#include <zconf.h>

CReinforcementTypeMnemonics::CReinforcementTypeMnemonics() : 
CMnemonicsCollector<int>( NDb::_RT_NONE, "_RT_NONE" )
{
	Insert( NDb::RT_MAIN_INFANTRY, "RT_MAIN_INFANTRY" );
	Insert( NDb::RT_ASSAULT_INFANTRY, "RT_ASSAULT_INFANTRY" );
	Insert( NDb::RT_ARTILLERY_ANTITANK, "RT_ARTILLERY_ANTITANK" );
	Insert( NDb::RT_ARTILLERY, "RT_ARTILLERY" );
	Insert( NDb::RT_ASSAULT_GUNS, "RT_ASSAULT_GUNS" );
	Insert( NDb::RT_TANK_DESTROYERS, "RT_TANK_DESTROYERS" );
	Insert( NDb::RT_ARTILLERY_ROCKET, "RT_ARTILLERY_ROCKET" );
	Insert( NDb::RT_LIGHT_TANKS, "RT_LIGHT_TANKS" );
	Insert( NDb::RT_TANKS, "RT_TANKS" );
	Insert( NDb::RT_HEAVY_TANKS, "RT_HEAVY_TANKS" );
	Insert( NDb::RT_LIGHT_AAA, "RT_LIGHT_AAA" );
	Insert( NDb::RT_HEAVY_AAA, "RT_HEAVY_AAA" );
	Insert( NDb::RT_FIGHTERS, "RT_FIGHTERS" );
	Insert( NDb::RT_BOMBERS, "RT_BOMBERS" );
	Insert( NDb::RT_GROUND_ATTACK_PLANES, "RT_GROUND_ATTACK_PLANES" );
	Insert( NDb::RT_RECON, "RT_RECON" );
	Insert( NDb::RT_PARATROOPS, "RT_PARATROOPS" );
	Insert( NDb::RT_ENGINEERING, "RT_ENGINEERING" );
	Insert( NDb::RT_HEAVY_ARTILLERY, "RT_HEAVY_ARTILLERY" );
	Insert( NDb::RT_EXTRA_GROUND_1, "RT_EXTRA_GROUND_1" );
	Insert( NDb::RT_EXTRA_GROUND_2, "RT_EXTRA_GROUND_2" );
	Insert( NDb::RT_EXTRA_GROUND_3, "RT_EXTRA_GROUND_3" );
	Insert( NDb::RT_EXTRA_GROUND_4, "RT_EXTRA_GROUND_4" );
	Insert( NDb::RT_EXTRA_GROUND_5, "RT_EXTRA_GROUND_5" );
	Insert( NDb::RT_EXTRA_GROUND_6, "RT_EXTRA_GROUND_6" );
	Insert( NDb::RT_EXTRA_GROUND_7, "RT_EXTRA_GROUND_7" );
	Insert( NDb::RT_EXTRA_GROUND_8, "RT_EXTRA_GROUND_8" );
	Insert( NDb::RT_EXTRA_GROUND_9, "RT_EXTRA_GROUND_9" );
	Insert( NDb::RT_EXTRA_GROUND_10, "RT_EXTRA_GROUND_10" );
	Insert( NDb::RT_EXTRA_AIR_1, "RT_EXTRA_AIR_1" );
	Insert( NDb::RT_EXTRA_AIR_2, "RT_EXTRA_AIR_2" );
	Insert( NDb::RT_EXTRA_AIR_3, "RT_EXTRA_AIR_3" );
	Insert( NDb::RT_EXTRA_AIR_4, "RT_EXTRA_AIR_4" );
	Insert( NDb::RT_EXTRA_AIR_5, "RT_EXTRA_AIR_5" );
	Insert( NDb::RT_EXTRA_MAXLVL_GROUND_1, "RT_EXTRA_MAXLVL_GROUND_1" );
	Insert( NDb::RT_EXTRA_MAXLVL_GROUND_2, "RT_EXTRA_MAXLVL_GROUND_2" );
	Insert( NDb::RT_EXTRA_MAXLVL_GROUND_3, "RT_EXTRA_MAXLVL_GROUND_3" );
	Insert( NDb::RT_EXTRA_MAXLVL_GROUND_4, "RT_EXTRA_MAXLVL_GROUND_4" );
	Insert( NDb::RT_EXTRA_MAXLVL_GROUND_5, "RT_EXTRA_MAXLVL_GROUND_5" );
	Insert( NDb::RT_EXTRA_MAXLVL_AIR_1, "RT_EXTRA_MAXLVL_AIR_1" );
	Insert( NDb::RT_EXTRA_MAXLVL_AIR_2, "RT_EXTRA_MAXLVL_AIR_2" );
	Insert( NDb::RT_EXTRA_MAXLVL_AIR_3, "RT_EXTRA_MAXLVL_AIR_3" );
	Insert( NDb::RT_EXTRA_MAXLVL_AIR_4, "RT_EXTRA_MAXLVL_AIR_4" );
	Insert( NDb::RT_EXTRA_MAXLVL_AIR_5, "RT_EXTRA_MAXLVL_AIR_5" );
	Insert( NDb::RT_EXTRA_MAXLVL_MIXED_1, "RT_EXTRA_MAXLVL_MIXED_1" );
	Insert( NDb::RT_EXTRA_MAXLVL_MIXED_2, "RT_EXTRA_MAXLVL_MIXED_2" );
	Insert( NDb::RT_EXTRA_MAXLVL_MIXED_3, "RT_EXTRA_MAXLVL_MIXED_3" );
	Insert( NDb::RT_EXTRA_MAXLVL_MIXED_4, "RT_EXTRA_MAXLVL_MIXED_4" );
	Insert( NDb::RT_EXTRA_MAXLVL_MIXED_5, "RT_EXTRA_MAXLVL_MIXED_5" );
	Insert( NDb::_RT_NONE, "_RT_NONE" );
}

CReinforcementTypeMnemonics typeReinforcementMnemonics;


