#include "stdafx.h"

#include "InternalPackets.h"

REGISTER_SAVELOAD_CLASS( TESTCLIENT, 0x3012B380, CEnteredLobby )
REGISTER_SAVELOAD_CLASS( TESTCLIENT, 0x30134B01, CTestShowGameClients )

REGISTER_SAVELOAD_CLASS( TESTCLIENT, 90, CTestSpecGameInfo )


