#pragma once

#define VENDOR_ADVANCED_MICRO_DEVICES_INC_AMDATI 0x1002
#define VENDOR_NVIDIA_CORPORATION 0x10de
#define VENDOR_GIGABYTE_TECHNOLOGY_CO_LTD 0x1458
#define VENDOR_MICROSTAR_INTERNATIONAL_CO_LTD_MSI 0x1462
#define VENDOR_TUL_CORPORATION_POWERCOLOR 0x148c
#define VENDOR_XFX_PINE_GROUP_INC 0x1682
#define VENDOR_SAPPHIRE_TECHNOLOGY_LIMITED 0x1da2
#define VENDOR_INTEL_CORPORATION 0x8086
