set(ARCHITECTURE "NONE" CACHE STRING "CPU architecture")
set_property(CACHE ARCHITECTURE PROPERTY STRINGS NONE SSE2 AVX AVX2 AVX512)

if(MSVC)
    if(ARCHITECTURE STREQUAL "SSE2")
        add_compile_options("/arch:SSE2")
    elseif(ARCHITECTURE STREQUAL "AVX")
        add_compile_options("/arch:AVX")
    elseif(ARCHITECTURE STREQUAL "AVX2")
        add_compile_options("/arch:AVX2")
    elseif(ARCHITECTURE STREQUAL "AVX512")
        add_compile_options("/arch:AVX512")
    endif()
endif()
