# Write the source tree's git revision into a header, run as a build step.
#
# A build step rather than a configure-time execute_process, because a
# configure-time revision is the one the tree had when CMake last ran: a local
# build made after a commit or a checkout would name a revision it was not
# built from, which is worse in a bug report than naming none. The header is
# rewritten only when its text changes (configure_file COPYONLY), and the
# custom target declares it a byproduct, so Ninja rebuilds what includes it
# only after the revision has actually moved.
#
# Invoked as:
#   cmake -DGIT_SOURCE_DIR=<dir> -DGIT_REVISION_HEADER=<file> -P gitrevision.cmake
#
# Defines GIT_REVISION_STR (short hash, "-dirty" when tracked files differ
# from it), GIT_BRANCH_STR and GIT_COMMIT_DATE_STR; each is "unknown" when git
# or the repository is not there, as in a source archive.

if(NOT DEFINED GIT_SOURCE_DIR OR NOT DEFINED GIT_REVISION_HEADER)
    message(FATAL_ERROR "gitrevision.cmake needs GIT_SOURCE_DIR and GIT_REVISION_HEADER")
endif()

set(GIT_REVISION "unknown")
set(GIT_BRANCH "unknown")
set(GIT_COMMIT_DATE "unknown")

find_program(GIT_EXECUTABLE git)
if(GIT_EXECUTABLE)
    execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --short=10 HEAD
        WORKING_DIRECTORY ${GIT_SOURCE_DIR}
        OUTPUT_VARIABLE GIT_OUT OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
        RESULT_VARIABLE GIT_RESULT)
    if(GIT_RESULT EQUAL 0 AND GIT_OUT)
        set(GIT_REVISION "${GIT_OUT}")
        # Tracked files only: build output and scratch files in the tree are not
        # a change to the source.
        execute_process(COMMAND ${GIT_EXECUTABLE} status --porcelain --untracked-files=no
            WORKING_DIRECTORY ${GIT_SOURCE_DIR}
            OUTPUT_VARIABLE GIT_OUT OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
            RESULT_VARIABLE GIT_RESULT)
        if(GIT_RESULT EQUAL 0 AND GIT_OUT)
            string(APPEND GIT_REVISION "-dirty")
        endif()
        # CI checks out a detached HEAD; GitHub names the branch or tag it built.
        if(DEFINED ENV{GITHUB_REF_NAME})
            set(GIT_BRANCH "$ENV{GITHUB_REF_NAME}")
        else()
            execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD
                WORKING_DIRECTORY ${GIT_SOURCE_DIR}
                OUTPUT_VARIABLE GIT_OUT OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
                RESULT_VARIABLE GIT_RESULT)
            if(GIT_RESULT EQUAL 0 AND GIT_OUT)
                set(GIT_BRANCH "${GIT_OUT}")
            endif()
        endif()
        execute_process(COMMAND ${GIT_EXECUTABLE} log -1 --format=%cd --date=iso
            WORKING_DIRECTORY ${GIT_SOURCE_DIR}
            OUTPUT_VARIABLE GIT_OUT OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
            RESULT_VARIABLE GIT_RESULT)
        if(GIT_RESULT EQUAL 0 AND GIT_OUT)
            set(GIT_COMMIT_DATE "${GIT_OUT}")
        endif()
    endif()
endif()

set(GIT_HEADER_TEXT "// Generated by cmake/gitrevision.cmake at build time. Do not edit.
#pragma once
#define GIT_REVISION_STR \"${GIT_REVISION}\"
#define GIT_BRANCH_STR \"${GIT_BRANCH}\"
#define GIT_COMMIT_DATE_STR \"${GIT_COMMIT_DATE}\"
")
file(WRITE "${GIT_REVISION_HEADER}.tmp" "${GIT_HEADER_TEXT}")
configure_file("${GIT_REVISION_HEADER}.tmp" "${GIT_REVISION_HEADER}" COPYONLY)
file(REMOVE "${GIT_REVISION_HEADER}.tmp")
