#!/usr/bin/env python3
"""Regenerate Versions/Temporary/Engine/Sources/vendor/d3d9stub/src/Caps.inc.

The stub d3d9.dll answers IDirect3D9::GetDeviceCaps with a real card's caps,
because the engine branches on them: 3Dmotor/Gfx.cpp reads ten fields and picks
its shader, texture and vertex processing paths from them, and made-up caps
send it down a path that fails somewhere else entirely. So they are captured
from the D3D9 device on the machine running this, once, and committed.

It asks Direct3DCreate9 and IDirect3D9::GetDeviceCaps and nothing else: no
window and no device, so it takes no input and puts nothing on screen. It does
need the real d3d9.dll and a desktop D3D9 will talk to -- run it on the
interactive desktop, not on bk2probe, where CheckDeviceType already fails.

The field list comes from the SDK's own d3d9caps.h rather than being typed
here, so the offsets are the header's and the output names every field.

Usage:
    python scripts/port/gen-d3d9-caps.py            # write Caps.inc
    python scripts/port/gen-d3d9-caps.py --print    # show it, write nothing
"""
import argparse
import ctypes as C
import os
import re
import struct
import sys
from ctypes import wintypes

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT_PATH = os.path.join(ROOT, 'Versions', 'Temporary', 'Engine', 'Sources', 'vendor', 'd3d9stub',
                        'src', 'Caps.inc')
DXSDK = os.environ.get('DXSDK_ROOT', r'C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)')
CAPS_HEADER = os.path.join(DXSDK, 'Include', 'd3d9caps.h')

D3D_SDK_VERSION = 32
D3DDEVTYPE_HAL = 1
# IUnknown's three, then IDirect3D9 in declaration order up to GetDeviceCaps.
VTBL_GET_ADAPTER_IDENTIFIER = 5
VTBL_GET_DEVICE_CAPS = 14

# The two nested structs, by field. Everything in them is four bytes wide.
NESTED = {
    'D3DVSHADERCAPS2_0': ['Caps', 'DynamicFlowControlDepth', 'NumTemps', 'StaticFlowControlDepth'],
    'D3DPSHADERCAPS2_0': ['Caps', 'DynamicFlowControlDepth', 'NumTemps', 'StaticFlowControlDepth',
                          'NumInstructionSlots'],
}
SIGNED = {'DynamicFlowControlDepth', 'NumTemps', 'StaticFlowControlDepth', 'NumInstructionSlots'}


def caps_fields():
    """[(name, kind)] for D3DCAPS9 in order; kind is 'u', 'i', 'f' or 'devtype'."""
    text = open(CAPS_HEADER, encoding='latin-1').read()
    body = re.search(r'typedef struct _D3DCAPS9\s*\{(.*?)\}\s*D3DCAPS9;', text, re.S).group(1)
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    body = re.sub(r'//[^\n]*', '', body)
    fields = []
    for decl in body.split(';'):
        decl = decl.strip()
        if not decl:
            continue
        type_, names = decl.split(None, 1)
        for name in (n.strip() for n in names.split(',')):
            if type_ in NESTED:
                for sub in NESTED[type_]:
                    fields.append(('%s.%s' % (name, sub), 'i' if sub in SIGNED else 'u'))
            elif type_ == 'float':
                fields.append((name, 'f'))
            elif type_ == 'D3DDEVTYPE':
                fields.append((name, 'devtype'))
            elif type_ in ('DWORD', 'UINT'):
                fields.append((name, 'u'))
            else:
                raise SystemExit('unknown field type %r in D3DCAPS9' % type_)
    return fields


def method(obj, index, restype, argtypes):
    vtable = C.cast(obj, C.POINTER(C.POINTER(C.c_void_p)))[0]
    return C.WINFUNCTYPE(restype, *argtypes)(vtable[index])


def capture(size):
    d3d9 = C.WinDLL('d3d9')
    d3d9.Direct3DCreate9.argtypes = [wintypes.UINT]
    d3d9.Direct3DCreate9.restype = C.c_void_p
    p = d3d9.Direct3DCreate9(D3D_SDK_VERSION)
    if not p:
        raise SystemExit('Direct3DCreate9 returned NULL')
    buf = C.create_string_buffer(size)
    hr = method(p, VTBL_GET_DEVICE_CAPS, C.c_long,
                [C.c_void_p, wintypes.UINT, C.c_int, C.c_void_p])(p, 0, D3DDEVTYPE_HAL, buf)
    if hr != 0:
        raise SystemExit('GetDeviceCaps failed: 0x%08X' % (hr & 0xFFFFFFFF))
    # D3DADAPTER_IDENTIFIER9 opens with Driver[512] and Description[512]; only
    # the description is kept, to say in the output where the numbers came from.
    ident = C.create_string_buffer(1100)
    method(p, VTBL_GET_ADAPTER_IDENTIFIER, C.c_long,
           [C.c_void_p, wintypes.UINT, wintypes.DWORD, C.c_void_p])(p, 0, 0, ident)
    description = ident.raw[512:1024].split(b'\0', 1)[0].decode('latin-1')
    return buf.raw, description


def render(fields, raw, description):
    lines = [
        '// Generated by scripts/port/gen-d3d9-caps.py -- do not edit by hand.',
        '//',
        '// IDirect3D9::GetDeviceCaps( 0, D3DDEVTYPE_HAL ) as the real d3d9.dll answered',
        '// it for "%s". Included into the body of' % description,
        '// ND3D9Stub::FillCaps, where `caps` is the D3DCAPS9 being filled.',
        '',
    ]
    for n, (name, kind) in enumerate(fields):
        word = raw[n * 4:n * 4 + 4]
        if kind == 'f':
            value = struct.unpack('<f', word)[0]
            text = '%.9gf' % value
            if 'e' not in text and '.' not in text and 'inf' not in text:
                text = text[:-1] + '.0f'
        elif kind == 'i':
            text = '%d' % struct.unpack('<i', word)[0]
        elif kind == 'devtype':
            text = 'static_cast<D3DDEVTYPE>( %d )' % struct.unpack('<I', word)[0]
        else:
            text = '0x%08X' % struct.unpack('<I', word)[0]
        lines.append('caps.%s = %s;' % (name, text))
    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--print', action='store_true')
    args = ap.parse_args()
    fields = caps_fields()
    size = 4 * len(fields)
    if size != 304:
        raise SystemExit('parsed D3DCAPS9 as %d bytes; sizeof is 304' % size)
    raw, description = capture(size)
    text = render(fields, raw, description)
    if args.print:
        sys.stdout.write(text)
        return 0
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, 'w', newline='\n') as f:
        f.write(text)
    print('wrote %s (%d fields, from "%s")' % (OUT_PATH, len(fields), description))
    return 0


if __name__ == '__main__':
    sys.exit(main())
