#!/usr/bin/env python3
"""Regenerate Versions/Temporary/Engine/Sources/vendor/granny/GrannyStub.cpp.

Granny is proprietary and ships as a Windows .lib and .dll only, so off Windows
the entry points this tree references are stubbed, and each stub records that it
was called, in what order and with what arguments. See the comment at the top of
the generated file, and PORT_ROADMAP.md's "Granny, and the log that says what to
port".

The stub is committed rather than generated during the build, because generating
it needs two things that are not build inputs: the vendored granny211.h, and the
list of symbols the link is actually missing. Run this when that list changes -
when a function starts being called, or stops, or when one of them is really
implemented and should come out of the stub.

Usage:
    scripts/port/gen-granny-stub.py [symbol-list]

    symbol-list   one symbol per line. Defaults to scripts/port/granny-symbols.txt.

To refresh the symbol list from a failing link:

    ninja -k 0 2>&1 | grep -oE "undefined reference to .Granny[^'\\"]*" \\
        | sed "s/undefined reference to .//" | sort -u > scripts/port/granny-symbols.txt
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))

HEADER_PATH = os.path.join(ROOT, 'third_party', 'uesp-esoapps', 'common', 'granny', 'granny211.h')
OUT_PATH = os.path.join(ROOT, 'Versions', 'Temporary', 'Engine', 'Sources', 'vendor', 'granny',
                        'GrannyStub.cpp')
DEFAULT_SYMBOLS = os.path.join(HERE, 'granny-symbols.txt')

# GRANNY_DYNLINK(rettype) Name(args); - the declarations may span lines
DECL_RE = re.compile(r'GRANNY_DYNLINK\(\s*(.*?)\s*\)\s+(\w+)\s*\((.*?)\)\s*;', re.S)


def split_params(args):
    """Split a parameter list on top-level commas."""
    out, depth, cur = [], 0, ''
    for ch in args:
        if ch in '(<[':
            depth += 1
        elif ch in ')>]':
            depth -= 1
        if ch == ',' and depth == 0:
            out.append(cur.strip())
            cur = ''
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def param_name(p):
    """The declared name of a parameter, which every Granny declaration has."""
    return re.search(r'(\w+)\s*$', p).group(1)


def default_return(ret):
    """What a stub with nothing to say should hand back."""
    r = ret.strip()
    if r == 'void':
        return None
    if r.endswith('*'):
        return '0'
    if r == 'bool':
        return 'false'
    if r == 'granny_real32':
        return '0.0f'
    return '0'


PREAMBLE = r'''#include "vendor/granny/include/granny.h"

#include <fmt/format.h>

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <type_traits>
#include <vector>

// Granny 3D, stubbed off Windows, so that the calls can be watched rather than
// guessed at.
//
// Granny is proprietary and ships as a Windows .lib and .dll only; there is no
// Linux build to link and no system package to ask for. Porting it is its own
// project, and the first question that project has to answer is which of its
// entry points actually matter. Linking answers part of that already - these are
// what the tree references, out of the several hundred granny211.h declares -
// but a reference is not a call. Some of these sit on paths that cannot be
// reached with the data this game ships, and the linker has no way to know it.
//
// So every function here records that it was called, in what order, and with
// what arguments, and the whole picture is written out when the process ends.
// What comes back is the list to port, in the order it is needed.
//
// **Generated by scripts/port/gen-granny-stub.py. Do not edit by hand**: run
// that instead, after refreshing scripts/port/granny-symbols.txt from a failing
// link. It is committed rather than generated during the build because it needs
// granny211.h and the current undefined-symbol list together, and the second is
// not a build input.
//
// **Nothing here does any work.** Every call returns a null, a zero or a false,
// so the game will not animate and will very likely stop somewhere in loading.
// That is the intended outcome: the log up to that point is the deliverable.

namespace
{

//! Where the log goes, and when.
//!
//! Opened on first use rather than at load, so that the working directory is
//! whatever the game chose, and flushed on every line because the process this
//! is meant to observe is expected to stop abruptly.
FILE *Log()
{
	static FILE *pLog = fopen( "granny_calls.log", "w" );
	return pLog;
}

//! One Granny entry point, and what has been seen of it.
//!
//! Constructed once per function as a static local, so the registry below fills
//! itself in call order without anything having to list the functions twice.
class CCallSite
{
	const char *pszName;
	uint64_t nCalls;
	uint64_t nFirstOrdinal;

public:
	explicit CCallSite( const char *_pszName );

	const char *GetName() const { return pszName; }
	uint64_t GetCalls() const { return nCalls; }
	uint64_t GetFirstOrdinal() const { return nFirstOrdinal; }

	//! Count this call, and say whether it is one of the first few, which are
	//! the ones worth writing out in full. A per frame call would otherwise bury
	//! the sequence that leads up to it, and the sequence is the point.
	bool ShouldTrace();
};

std::vector<CCallSite *> &Registry()
{
	static std::vector<CCallSite *> registry;
	return registry;
}

uint64_t nCallOrdinal = 0;

// How many calls of each function are written out in full before only the count
// is kept.
const uint64_t TRACED_CALLS_PER_FUNCTION = 8;

//! What the whole run looked like, written when the process ends.
void DumpSummary()
{
	FILE *pLog = Log();
	if ( pLog == 0 )
	{
		return;
	}
	fmt::print( pLog, "\n=== {} Granny entry points called, {} calls in total ===\n",
	            Registry().size(), nCallOrdinal );
	fmt::print( pLog, "{:>8}  {:>12}  {}\n", "first", "calls", "function" );
	for ( std::vector<CCallSite *>::const_iterator it = Registry().begin(); it != Registry().end(); ++it )
	{
		fmt::print( pLog, "{:>8}  {:>12}  {}\n", ( *it )->GetFirstOrdinal(), ( *it )->GetCalls(),
		            ( *it )->GetName() );
	}
	fflush( pLog );
}

CCallSite::CCallSite( const char *_pszName ) : pszName( _pszName ), nCalls( 0 ), nFirstOrdinal( 0 )
{
	// The registry has to outlive every call site, and a function local static
	// is destroyed in reverse order of construction, so registering here is what
	// keeps the vector alive for as long as anything can reach it.
	static const bool bSummaryRegistered = ( atexit( DumpSummary ), true );
	(void)bSummaryRegistered;
	Registry().push_back( this );
}

bool CCallSite::ShouldTrace()
{
	++nCalls;
	++nCallOrdinal;
	if ( nCalls == 1 )
	{
		nFirstOrdinal = nCallOrdinal;
	}
	return nCalls <= TRACED_CALLS_PER_FUNCTION;
}

//! An argument in a form fmt can print.
//!
//! A string is worth more than the pointer to it - it names the model being
//! loaded - so those are passed through. Every other pointer becomes an opaque
//! address, which is enough to match a later call against an earlier one, and an
//! enum becomes its number.
template <typename T>
auto Loggable( T v )
{
	if constexpr ( std::is_same_v<T, const char *> || std::is_same_v<T, char *> )
	{
		return v != 0 ? std::string( v ) : std::string( "(null)" );
	}
	else if constexpr ( std::is_pointer_v<T> && std::is_function_v<std::remove_pointer_t<T>> )
	{
		// A function pointer is not an object pointer and cannot be cast to
		// void*. granny_allocate_callback is one of these, and GrannySetAllocator
		// is where the engine installs its own, so it is worth seeing.
		return reinterpret_cast<uintptr_t>( v );
	}
	else if constexpr ( std::is_pointer_v<T> )
	{
		return static_cast<const void *>( v );
	}
	else if constexpr ( std::is_enum_v<T> )
	{
		return static_cast<int>( v );
	}
	else
	{
		return v;
	}
}

template <typename... TArgs>
void TraceCall( const CCallSite &site, fmt::format_string<TArgs...> fmtArgs, TArgs &&...args )
{
	FILE *pLog = Log();
	if ( pLog == 0 )
	{
		return;
	}
	fmt::print( pLog, "{:>8}  {}( ", nCallOrdinal, site.GetName() );
	fmt::print( pLog, fmtArgs, std::forward<TArgs>( args )... );
	fmt::print( pLog, " )\n" );
	fflush( pLog );
}

}
'''


def main():
    symbols_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SYMBOLS
    symbols = io.open(symbols_path, encoding='utf-8').read().split()

    src = io.open(HEADER_PATH, encoding='utf-8', errors='replace').read()
    declared = {}
    for m in DECL_RE.finditer(src):
        declared[m.group(2)] = (m.group(1), ' '.join(m.group(3).split()))

    missing = [s for s in symbols if s not in declared]
    if missing:
        sys.stderr.write('not declared in granny211.h: %s\n' % ', '.join(missing))
        return 1

    out = [PREAMBLE, '\nextern "C"\n{\n']
    for s in symbols:
        ret, args = declared[s]
        params = split_params(args)
        names = [param_name(p) for p in params]
        out.append('GRANNY_DYNLINK( %s ) %s( %s )\n{\n' % (ret, s, ', '.join(params) if params else 'void'))
        out.append('\tstatic CCallSite site( "%s" );\n' % s)
        if names:
            out.append('\tif ( site.ShouldTrace() )\n\t{\n')
            out.append('\t\tTraceCall( site, "%s", %s );\n' % (
                ' '.join('%s={}' % n for n in names),
                ', '.join('Loggable( %s )' % n for n in names)))
            out.append('\t}\n')
        else:
            out.append('\tsite.ShouldTrace();\n')
        ret_value = default_return(ret)
        if ret_value is not None:
            out.append('\treturn %s;\n' % ret_value)
        out.append('}\n\n')
    out.append('}\n')

    io.open(OUT_PATH, 'w', encoding='utf-8', newline='').write(''.join(out))
    sys.stderr.write('wrote %s with %d stubs\n' % (os.path.relpath(OUT_PATH, ROOT), len(symbols)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
