#!/usr/bin/env python3
"""Regenerate Versions/Temporary/Engine/Sources/vendor/libgr2/src/Shim.cpp.

The shim is a granny2_x64.dll that logs every call the way libgr2 does and then
hands it to the real granny2. It exists so that the same play can be recorded
twice, once against each implementation, and the two logs diffed. Everything that
makes them comparable is shared code rather than generated: Trace.h gives objects
stable ids instead of addresses, and Identify.h names files by the hash of their
bytes, so the same resource reads the same in both logs.

The 54 forwarders themselves are mechanical, which is why they are generated
rather than written. They are generated from libgr2's own public header, not from
granny211.h, for two reasons: the header is the one both DLLs are compiled
against, so the signatures cannot drift apart, and it keeps the shim inside a
library that otherwise depends on nothing but spdlog.

The output is committed, because generating it during the build would put Python
on the critical path for a target that changes only when the API does.

Usage:
    scripts/port/gen-granny-shim.py
    scripts/port/gen-granny-shim.py --check     exit 1 if the file is stale

Run it when include/gr2/granny.h gains, loses or changes an entry point, or when
HOOKS below needs a new one.
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
LIBGR2 = os.path.join(ROOT, 'Versions', 'Temporary', 'Engine', 'Sources', 'vendor', 'libgr2')
HEADER_PATH = os.path.join(LIBGR2, 'include', 'gr2', 'granny.h')
EXPORTS_PATH = os.path.join(LIBGR2, 'exports.txt')
OUT_PATH = os.path.join(LIBGR2, 'src', 'Shim.cpp')

# GR2_API( ret ) Name( params ); - declarations may span lines.
DECL_RE = re.compile(r'GR2_API\(\s*(.*?)\s*\)\s+(\w+)\s*\((.*?)\)\s*;', re.S)

# The handful of entry points that are more than a forwarder, because the shared
# registry has to be told what the real DLL just did. Statements run either side
# of the forwarded call; `Result` names its return value where there is one.
#
# The asymmetry worth knowing about is GrannyFreeModelInstance. libgr2 frees the
# controls bound to an instance along with it and retires their ids too; from out
# here they cannot be enumerated, so a control id can outlive its control in the
# shim's log and be reused by the next control at the same address. It shows up
# as a control that appears to be bound twice, and only after a free.
HOOKS = {
    'GrannyReadEntireFile': (
        [],
        # No hash on this route: the bytes are the real DLL's and never come back
        # out. The path is better identity anyway, and the game never takes this
        # route, only the editor and SceneB2/TerraTools.cpp.
        ['NGr2::NoteFileName( Result, FileName );'],
    ),
    'GrannyReadEntireFileFromMemory': (
        [],
        ['NGr2::NoteFileBytes( Result, Memory,\n'
         '\t                      MemorySize > 0 ? static_cast<size_t>( MemorySize ) : 0u );'],
    ),
    'GrannyGetFileInfo': (
        [],
        ['NGr2::NoteFileInfo( File, reinterpret_cast<const NGr2::SFileInfo *>( Result ) );'],
    ),
    'GrannyFreeFile': (
        ['NGr2::ForgetFile( File );', 'NGr2::RetireHandle( File );'],
        [],
    ),
    # Not a free, but the builder is consumed here and the real DLL's allocator
    # hands the same address straight back to the next one. Without retiring it
    # the second builder inherits the first one's number and the two logs differ
    # over nothing.
    'GrannyEndControlledAnimation': (['NGr2::RetireHandle( Builder );'], []),
    'GrannyFreeLocalPose': (['NGr2::RetireHandle( LocalPose );'], []),
    'GrannyFreeWorldPose': (['NGr2::RetireHandle( WorldPose );'], []),
    'GrannyFreeModelInstance': (['NGr2::RetireHandle( ModelInstance );'], []),
    'GrannyFreeControl': (['NGr2::RetireHandle( Control );'], []),
}

PREAMBLE = '''// Generated by scripts/port/gen-granny-shim.py. Do not edit.
//
// A granny2 that records and forwards. Every entry point logs its arguments the
// way libgr2's own does, in the same format and with the same stable object ids,
// and then calls the real DLL. Two runs of the same play, one against each, give
// two logs that diff.
//
// Built as the `gr2-shim` target, which is Windows only and always defines
// LIBGR2_TRACE_CALLS: a shim with the trace compiled out would do nothing at all
// but slow the game down. See ShimLoader.h for which DLL it forwards to.
//
// The trace lines here are `Parameter={}` for each parameter in declaration
// order, which is the convention every hand-written GR2_TRACE in this library
// follows. That is what makes the two logs line up.

#include <gr2/granny.h>

#if defined( _WIN32 )

#include "Identify.h"
#include "ShimLoader.h"
#include "Structures.h"
#include "Trace.h"

#include <cstddef>

extern "C"
{
'''

EPILOGUE = '''
}

#endif
'''


def split_params(args):
    """Split a parameter list on top-level commas."""
    out, depth, cur = [], 0, ''
    for ch in args:
        if ch in '(<[':
            depth += 1
        elif ch in ')>]':
            depth -= 1
        if ch == ',' and depth == 0:
            out.append(' '.join(cur.split()))
            cur = ''
        else:
            cur += ch
    if cur.strip():
        out.append(' '.join(cur.split()))
    return out


def parameter_name(decl):
    """The identifier a parameter declaration ends with."""
    m = re.search(r'(\w+)\s*$', decl)
    if not m:
        raise SystemExit('unnamed parameter %r: the shim needs every parameter '
                         'named, to trace it and to forward it' % decl)
    return m.group(1)


def declarations(header):
    """Every GR2_API declaration, as (return type, name, [parameter declarations])."""
    out = []
    for ret, name, args in DECL_RE.findall(header):
        params = [p for p in split_params(args) if p not in ('void', '')]
        out.append((' '.join(ret.split()), name, params))
    return out


def render(ret, name, params):
    """One forwarder."""
    names = [parameter_name(p) for p in params]
    before, after = HOOKS.get(name, ([], []))
    is_void = ret == 'void'

    signature = ', '.join(params) if params else ''
    lines = ['GR2_API( %s ) %s( %s )' % (ret, name, signature), '{']

    trace_format = ' '.join('%s={}' % n for n in names)
    if names:
        lines.append('\tGR2_TRACE( "%s", %s );' % (trace_format, ', '.join(names)))
    else:
        lines.append('\tGR2_TRACE( "" );')
    lines.append('')

    lines.append('\ttypedef %s( __stdcall *TFn )( %s );' % (ret + ' ' if not ret.endswith('*')
                                                            else ret, signature))
    if not is_void:
        lines.append('\ttypedef %s TResult;' % ret)
    lines.append('\tstatic const TFn pfn = reinterpret_cast<TFn>( NGr2::ShimEntry( "%s" ) );'
                 % name)
    lines.append('\tif ( pfn == 0 )')
    lines.append('\t{')
    lines.append('\t\treturn%s;' % ('' if is_void else ' TResult()'))
    lines.append('\t}')

    for statement in before:
        lines.append('\t' + statement)
    if before:
        lines.append('')

    call = 'pfn( %s )' % ', '.join(names) if names else 'pfn()'
    if is_void:
        lines.append('\t%s;' % call)
    else:
        lines.append('\tTResult Result = %s;' % call)

    if after:
        lines.append('')
        for statement in after:
            lines.append('\t' + statement)

    if not is_void:
        lines.append('\treturn Result;')
    lines.append('}')
    return '\n'.join(lines)


def generate():
    with open(HEADER_PATH, encoding='utf-8') as f:
        header = f.read()
    with open(EXPORTS_PATH, encoding='utf-8') as f:
        exports = [line.strip() for line in f if line.strip()]

    by_name = {name: (ret, name, params) for ret, name, params in declarations(header)}
    missing = [name for name in exports if name not in by_name]
    if missing:
        raise SystemExit('exports.txt names %d entry points that %s does not declare: %s'
                         % (len(missing), os.path.basename(HEADER_PATH), ', '.join(missing)))
    unknown = [name for name in HOOKS if name not in by_name]
    if unknown:
        raise SystemExit('HOOKS names entry points that do not exist: %s' % ', '.join(unknown))

    bodies = [render(*by_name[name]) for name in exports]
    return PREAMBLE + '\n' + '\n\n'.join(bodies) + '\n' + EPILOGUE


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true',
                        help='do not write, exit 1 if the committed file is stale')
    args = parser.parse_args(argv[1:])

    text = generate()
    if args.check:
        current = ''
        if os.path.exists(OUT_PATH):
            with open(OUT_PATH, encoding='utf-8') as f:
                current = f.read()
        if current != text:
            print('%s is stale, rerun %s' % (OUT_PATH, os.path.basename(__file__)))
            return 1
        print('%s is up to date' % OUT_PATH)
        return 0

    with open(OUT_PATH, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('wrote %s, %d entry points' % (OUT_PATH, text.count('GR2_API(') - 0))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
