"""Regenerate CodePageTables.inc from Windows itself.

    python gen_codepages.py > CodePageTables.inc      (on Windows)

FontGen used to translate each byte it bakes through TranslateCharsetInfo and
MultiByteToWideChar( ..., MB_ERR_INVALID_CHARS, ... ), one byte at a time.
This asks Windows the same questions and records the answers, so that FontGen
gives identical results on any platform without calling Windows. A 0 in a
table is a byte Windows refused, which FontGen leaves out.

Only the upper half is stored: for every code page here the bytes 0x20..0x7F
are the identity, which this checks rather than assumes.
"""
import ctypes
import sys
from ctypes import wintypes


class CHARSETINFO(ctypes.Structure):
    _fields_ = [('ciCharset', wintypes.UINT), ('ciACP', wintypes.UINT), ('fs', wintypes.DWORD * 6)]


# every single-byte and double-byte code page a FontGen charset translates to;
# SYMBOL (42) is not here, see CodePages.cpp
CHARSETS = [('ANSI', 0), ('SHIFTJIS', 128), ('HANGUL', 129), ('GB2312', 134), ('CHINESEBIG5', 136),
            ('GREEK', 161), ('TURKISH', 162), ('HEBREW', 177), ('ARABIC', 178), ('BALTIC', 186),
            ('RUSSIAN', 204), ('THAI', 222), ('EASTEUROPE', 238)]
MB_ERR_INVALID_CHARS = 8
kernel = ctypes.windll.kernel32


def translate(page, byte):
    src = ctypes.c_char(bytes([byte]))
    dst = ctypes.c_wchar()
    n = kernel.MultiByteToWideChar(page, MB_ERR_INVALID_CHARS, ctypes.byref(src), 1, ctypes.byref(dst), 1)
    return ord(dst.value) if n == 1 else 0


def main():
    # LF, as the committed file has, rather than Windows' default of CRLF
    sys.stdout.reconfigure(newline='\n')
    out = sys.stdout
    out.write('// Generated by gen_codepages.py from Windows\' own MultiByteToWideChar. Do not\n')
    out.write('// edit by hand; rerun the script on Windows instead. Bytes 0x80..0xFF of each\n')
    out.write('// code page; 0 is a byte Windows refuses. Included by CodePages.cpp only.\n\n')
    pages = []
    for name, value in CHARSETS:
        info = CHARSETINFO()
        if not ctypes.windll.gdi32.TranslateCharsetInfo(ctypes.c_void_p(value), ctypes.byref(info), 1):
            sys.exit('no code page for %s' % name)
        page = info.ciACP
        for byte in range(0x20, 0x80):
            if translate(page, byte) != byte:
                sys.exit('code page %d is not the identity at 0x%02X' % (page, byte))
        pages.append((name, value, page))
    for page in sorted(set(p for _, _, p in pages)):
        out.write('static const uint16_t W_CP%d[128] =\n{\n' % page)
        row = [translate(page, byte) for byte in range(0x80, 0x100)]
        for i in range(0, 128, 8):
            out.write('\t' + ', '.join('0x%04X' % v for v in row[i:i + 8]) + ',\n')
        out.write('};\n\n')
    out.write('// charset -> table, as TranslateCharsetInfo pairs them\n')
    out.write('static const SCodePage CODE_PAGES[] =\n{\n')
    for name, value, page in pages:
        out.write('\t{ %d, %d, W_CP%d },\t// %s_CHARSET\n' % (value, page, page, name))
    out.write('};\n')


if __name__ == '__main__':
    main()
