project(AILogic)

if(MSVC)
    add_compile_options("/fp:strict")
endif()

set(SOURCES
    AAFeedBacks.cpp
    AckManager.cpp
    AIConsts.cpp
    AIDebugInfo.cpp
    AIGeometry.cpp
    AIGeometryDebug.cpp
    AILogicCommand.cpp
    AILogicCommands.cpp
    AILogicInternal.cpp
    AILogicSerialize.cpp
    AIMap.cpp
    AITimer.cpp
    AIUnit.cpp
    AIUnitInfoForGeneral.cpp
    AIUnitSerialize.cpp
    AllowFakeObjToCrushExecutor.cpp
    AnimUnitMech.cpp
    AnimUnitSoldier.cpp
    AntiArtillery.cpp
    AntiArtilleryManager.cpp
    AntiArtillerySerialize.cpp
    Artillery.cpp
    ArtilleryBulletStorage.cpp
    ArtilleryPaths.cpp
    ArtilleryStates.cpp
    ArtRocketStates.cpp
    Aviation.cpp
    B2AI.cpp
    BalanceTest.cpp
    Behaviour.cpp
    BehaviourSerialize.cpp
    Bridge.cpp
    BridgeCreation.cpp
    Building.cpp
    Cheats.cpp
    CLockWithUnlockPossibilities.cpp
    CollisionInternal.cpp
    CombatEstimator.cpp
    Commander.cpp
    CommandRegistratorForScript.cpp
    Commands.cpp
    CommonStates.cpp
    CommonUnit.cpp
    ComplexObstacleCreation.cpp
    CreateAI.cpp
    DamageToEnemyUpdater.cpp
    DBAIConsts.cpp
    DifficultyLevel.cpp
    Diplomacy.cpp
    EnemyRememberer.cpp
    Entrenchment.cpp
    EntrenchmentCreation.cpp
    Executor.cpp
    ExecutorAdrenalineRush.cpp
    ExecutorAmbush.cpp
    ExecutorAttackGroup.cpp
    ExecutorAttackGroupEvent.cpp
    ExecutorBurningFuel.cpp
    ExecutorCamouflage.cpp
    ExecutorCaution.cpp
    ExecutorContainer.cpp
    ExecutorCounterFire.cpp
    ExecutorExactShot.cpp
    ExecutorFormationFirstAid.cpp
    ExecutorLinkedGrenades.cpp
    ExecutorPlaceCharge.cpp
    ExecutorPlaneDropBombs.cpp
    ExecutorRestoreTransparencyQueue.cpp
    ExecutorSeaReinf.cpp
    ExecutorSimpleEvent.cpp
    ExecutorSmokeShots.cpp
    ExecutorSniperCamouflage.cpp
    ExecutorSoldierEntrench.cpp
    ExecutorSpyMode.cpp
    ExecutorStaticObjectSegment.cpp
    ExecutorThrowGrenade.cpp
    ExecutorTiming.cpp
    ExecutorTrackTargetting.cpp
    ExecutorTransportHealInfantry.cpp
    ExecutorUnitBase.cpp
    ExecutorUnitBonus.cpp
    ExecutorUnitCombatBonus.cpp
    ExecutorWatchForEnemyUnloadPassangers.cpp
    FakeObjects.cpp
    FeedbackSystem.cpp
    Fence.cpp
    FenceCreation.cpp
    Formation.cpp
    FormationEngineerStates.cpp
    FormationStates.cpp
    FreeFireManager.cpp
    GeneralAirForce.cpp
    GeneralArtillery.cpp
    GeneralConsts.cpp
    GeneralHelper.cpp
    GeneralIntendant.cpp
    GeneralInternal.cpp
    GeneralRearManager.cpp
    GeneralSerialize.cpp
    GeneralTasks.cpp
    GlobalObjects.cpp
    GlobalWarFog.cpp
    GlobeScriptHandler.cpp
    GlobeUpdater.cpp
    Graveyard.cpp
    GridCreation.cpp
    GroupLogic.cpp
    GroupLogicSerialize.cpp
    GroupMoveExecutor.cpp
    GroupMover.cpp
    GroupMoverNew.cpp
    Guns.cpp
    GunsSerialize.cpp
    HitsStore.cpp
    InBuildingStates.cpp
    InEntrenchmentStates.cpp
    InTransportStates.cpp
    KeyBuildingBonusSystem.cpp
    KillCorpseExecutor.cpp
    LinkObject.cpp
    ListsSet.cpp
    LongObjectCreation.cpp
    ManuverBuilder.cpp
    ManuverInternal.cpp
    ManuverStateDesc.cpp
    Mine.cpp
    MountedGun.cpp
    MountedGunsSerialize.cpp
    NewUpdater.cpp
    NewUpdaterTransformers.cpp
    ObjectProfile.cpp
    ObstacleInternal.cpp
    ParatrooperPath.cpp
    PathFractionArc.cpp
    PathFractionArc3D.cpp
    PathFractionArcLine3D.cpp
    PathFractionArcLineArc.cpp
    PathFractionArcLineArc3D.cpp
    PathFractionComplex.cpp
    PathFractionComposite.cpp
    PathFractionLine.cpp
    PathInternalSerialize.cpp
    PathSearchFuncs.cpp
    PlanePath.cpp
    PlanePathMath.cpp
    PlanePreferences.cpp
    PlanesFormation.cpp
    PlaneStates.cpp
    PlayerBonuses.cpp
    PlayerReinforcement.cpp
    PlayerResources.cpp
    PointChecking.cpp
    PredictedAntiAviationFire.cpp
    PresizePath.cpp
    Probability.cpp
    QueueUnit.cpp
    RailRoads.cpp
    Reinforcement.cpp
    ReinforcementPoints.cpp
    Resistance.cpp
    RndRunUpToEnemy.cpp
    RotatingFireplacesObject.cpp
    ScanLimiter.cpp
    Scripts.cpp
    ScriptsSerialize.cpp
    Shell.cpp
    ShellSerialize.cpp
    ShootEstimatorInternal.cpp
    ShootEstimatorSerialize.cpp
    SingleReinforcement.cpp
    SmokeScreen.cpp
    Soldier.cpp
    SoldierStates.cpp
    StaticMembers.cpp
    StaticObject.cpp
    StaticObjects.cpp
    StaticObjectsIters.cpp
    StaticObjectsSerialize.cpp
    Statistics.cpp
    StatusUpdatesHelper.cpp
    StdAfx.cpp
    StormableObject.cpp
    SupportAAGun.cpp
    SupremeBeing.cpp
    TankPitPath.cpp
    TankStates.cpp
    Technics.cpp
    TechnicStates.cpp
    TempBuffer.cpp
    TerraAIObserver.cpp
    TimeCounter.cpp
    TimerChargeExecutor.cpp
    TrainCar.cpp
    Trains.cpp
    TransportEngineerStates.cpp
    TransportStates.cpp
    Turret.cpp
    TurretSerialize.cpp
    UnderConstructionObject.cpp
    UnitCreation.cpp
    UnitGuns.cpp
    Units.cpp
    UnitsIterators.cpp
    UnitsSegments.cpp
    UnitsSerialize.cpp
    UnitStates.cpp
    UnitTorpedo.cpp
    UpdatableObject.cpp
    UpdateUnitContainer.cpp
    Weather.cpp
)
add_library(AILogic SHARED ${SOURCES})
add_export_header(AILogic)
add_stdafx_pch(AILogic)
target_link_libraries(AILogic PRIVATE B2_M1_Terrain B2_M1_World Common_RTS_AI DebugTools Input libdb MemoryLib Misc Script Stats_B2_M1 System zlib fmt::fmt-header-only)
if(WIN32)
    target_link_libraries(AILogic PRIVATE winapi)
endif()
install(TARGETS AILogic DESTINATION bin)
add_version_info(AILogic)
