/* Generated by Together */

#ifndef IPLANE_H
#define IPLANE_H

#pragma once

/**
 * самолет от этого наследуется.
 * @interface
 */
interface IPlane
{
public:
	// current speed
	virtual CVec3 GetSpeedB2() const = 0;
	// current position
	virtual CVec3 GetPosB2() const = 0;
	// current vertical direction
	virtual CVec3 GetNormalB2() const = 0;

	virtual const interface IManuver * GetManuver() const = 0;
	
	// next calculated position
	virtual CVec3 GetPosNext() const = 0;
	virtual CVec3 GetSpeedNext() const = 0;
	virtual CVec3 GetNormalNext() const = 0;
	
	virtual void SetB2( const CVec3 &vPos, const CVec3 &vSpeed, const CVec3 &vNormal ) = 0;

	/** текущий самолет уже находится под атакой. */
	virtual bool IsBeingAttackedB2() = 0;

	/** когда враг уже готовится стрелять в самолет. нужно для того, чтобы за 1 самолетом не гонялось несколько. */
	virtual void NotifyAttackedB2(IPlane & attacker, bool bAttack) = 0;

	// access to plane's preferences
	virtual const class CPlanePreferences & GetPreferencesB2() const = 0;
};
#endif //IPLANE_H

